<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>成都九九六网络科技有限公司-最好的手游发行渠道！</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/index.css"/>
</head>
<body>
<div class="container">
    <?php include $this->getScriptPath().'/header.phtml'; ?>
    <section class="swipe" id="slider" style="height:705px; overflow:hidden;">
        <figure class="swipe-wrap">
        <?php foreach ($banner['ads'] as $idx=>&$row) { ?>
            <a class="wrap" href="<?=$row['url']?>"<?=$row['target']?> style="background:url(<?=$row['image']?>) no-repeat scroll center top;"></a>
        <?php } ?>
        </figure>
        <ul class="select_btn" id="fade_bar">
        <?php foreach ($banner['ads'] as $idx=>&$row) { ?>
            <li<?php if($idx==0) echo ' class="selected"'; ?>></li>
        <?php } ?>
        </ul>
    </section>

    <section class="join">
        <h2 class="title">- 加入九九六/join  jiujiuliu -</h2>
        <nav class="join_nav">
            <a href="/documents/index.html">
                <i class="icons i_nav1"></i>
                <span>&nbsp;公司介绍 &gt;</span>
                <small>介绍成都九九六网络科技有限公司的相关业务。</small>
            </a>
            <a href="/nami/contactus.html">
                <i class="icons i_nav2"></i>
                <span>&nbsp;产品介绍 &gt;</span>
                <small>关于成都九九六网络科技有限公司的联系方式 。</small>
            </a>
            <a href="http://h5.zyttx.com">
                <i class="icons i_nav3"></i>
                <span>&nbsp;加入我们</span>
                <small>成都九九六网络科技有限公司战略合作游戏平台。</small>
            </a>
        </nav>
    </section>
    <section class="case">
        <h2 class="title">- 案例展示/case show-</h2>
        <div id="gallery">
            <div class="container_image">
                <ul id="myRoundabout">
                <?php foreach ($cases['ads'] as &$row) { ?>
                    <li><a href="<?=$row['url']?>"<?=$row['target']?> title="<?=$row['subject']?>"><img src="<?=$row['image']?>"></a></li>
                <?php } ?>
                </ul>
            </div>
        </div>
    </section>
<!--    <section class="game_lists">-->
<!--        <ul>-->
<!--        --><?php //foreach ($games['ads'] as $row) { ?>
<!--            <li>-->
<!--                <a href="--><?//=$row['url']?><!--"--><?//=$row['target']?><!-->
<!--                    <img src="--><?//=$row['image']?><!--" alt="--><?//=$row['subject']?><!--" />-->
<!--                    <span>--><?//=$row['subject']?><!--</span>-->
<!--                </a>-->
<!--            </li>-->
<!--        --><?php //} ?>
<!--        </ul>-->
<!--    </section>-->
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</div>
<script src="/js/jquery-1.4.2.min.js"></script>
<script src="/js/swipe.min.js"></script>
<script src="/js/jquery.roundabout.min.js"></script>
<script src="/js/jquery.easing.min.js"></script>
<script>
$('#top_nav a:eq(0)').addClass('selected');
$(function(){
    var banner = Swipe(document.getElementById('slider'), {
        auto: 4400,
        speed: 400,
        continuous: true,
        callback: function(index, element) {
        	index %= $("#fade_bar li").length;
            $("#fade_bar li").eq(index).addClass("selected").siblings().removeClass("selected");
        }
    });
    $("#fade_bar li").click(function(){
    	banner.slide($(this).index(), 400);
    });

    $('#myRoundabout').roundabout({
        minOpacity: 1,
        easing:'easeOutExpo'
    });
});
</script>
<?php include $this->getScriptPath().'/namiyx_wx.phtml'; ?>
</body>
</html>