<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<title>激活码详情 - 久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/pay_record.css"/>
</head>
<body class="bg01">
<!--div.container 总外框  start-->
<div  class="z_container">
    <header class="z_header">
        <a target="_top" href="/user/giftlogs.html"></a><span>激活码详情</span>
    </header>

    <!--div.z_min 内容区域 statr-->
    <div class="z_main" data-role="conent">
        <figure class="banner block_bg">
        <?php foreach ($banner['ads'] as &$row) { ?>
            <a target="_top" href="<?=$row['url']?>" class="line_01">
                <img src="<?=$row['image']?>" width="100%" height="auto"<?php if($row['subject']) echo " alt=\"{$row['subject']}\""; ?>/>
            </a>
        <?php } ?>
        </figure>
        <section class="pay_infos">
            <nav>
                <a style="width:100%"><span>礼包名称：</span><span class="bold"><?=$log['name']?></span></a>
            </nav>
            <ul>
            <?php if($log['game_id']) { ?>
                <li>
                    <span>所属游戏：</span>
                    <span class="bold"><?=$log['game_name']?></span>
                </li>
            <?php } ?>
            <?php if($log['server_id']) { ?>
                <li>
                    <span>所属区/服：</span>
                    <span class="bold"><?=$log['server_name']?></span>
                </li>
            <?php } ?>
            <?php if(empty($log['game_id']) && empty($log['server_id'])) { ?>
                <li>
                    <span>礼包来源：</span>
                    <span class="bold">平台活动</span>
                </li>
            <?php } ?>
                <li>
                    <span>激&nbsp;活&nbsp;码：</span>
                    <span><input class="cdkey" type="text" value="<?=$log['cdkey']?>" readonly="readonly"></span>
                </li>
                <li>
                    <span>领取时间：</span>
                    <span><?=date('Y-m-d H:i:s', $log['get_time'])?></span>
                </li>
            </ul>
        </section>
        <div class="footer_padding"></div>
    </div>
    <!--div.z_min 内容区域 end-->
</div>
<!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script>$('#footer a:eq(4)').attr('id', 'footer_nav_active');</script>
</body>
</html>