<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<title>个人中心 - 久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/user_center.css"/>
</head>
<body class="bg00">
<!--div.container 总外框  start-->
<div  class="z_container wrapper bg01">
    <!--div.z_min 内容区域 statr-->
    <div class="z_main">
    <?php if($user) { ?>
        <!--div.have_login 登录后信息 statr-->
        <div class="have_login" style="margin-top:0">
            <section class="user_info block_bg border_line">
                <figure class="fl user_img">
                <a target="_top" href="/user/edit.html">
                    <img src="<?=$user['avatar']?$user['avatar']:'/images/user_center/default_img.png'?>" alt="<?=$user['nickname']?$user['nickname']:$user['username']?>"/>
                </a>
                </figure>
                <ul class="fl information">
                    <li>
                        <i class="icons i_porstion"></i>
                        <span>欢迎您：</span>
                        <a><?=$user['nickname']?$user['nickname']:$user['username']?></a>
                    </li>
                    <li>
                        <i class="icons i_gold"></i>
                        <span>平台币：</span>
                        <a class="green"><?=number_format($user['money'])?>￥</a>
                    </li>
                    <li>
                        <i class="icons i_jf"></i>
                        <span>积分币：</span>
                        <a class="green"><?=number_format($user['integral'])?></a>
                    </li>
                </ul>
            </section>
            <nav class="nav_info block_bg">
                <a target="_top" href="/user/logout.html?fwd=/user/index.html">退出登录<span class="split_line"></span></a>
                <a target="_top" href="/user/giftlogs.html">礼包记录<span class="split_line"></span></a>
                <a target="_top" href="/user/paylogs.html">充值记录</a>
            </nav>
        </div>
        <!--div.have_login 登录后信息 end-->
    <?php } else { ?>
        <!--div.no_login 未登录的状态 statr-->
        <div class="no_login block_bg" style="margin-top:0">
            <div class="img_cont">
                <figure class="fl user_img">
                    <img src="/images/user_center/default_img.png"/>
                </figure>
            </div>
            <p class="tip_word">
<!--                <span class="urls">namiyx.com </span>-->
                <span class="green">您还未登录</span>，请您先登录平台。
            </p>
            <div class="btn_cont">
                <button class="btn_green" onclick="javascript:location.href='/user/login.html?fwd=/user/index.html';">登录平台</button>
            </div>
        </div>
        <!--div.no_login 未登录的状态 end-->
    <?php } ?>

        <!--nav.user_lists 用户信息分类列表 statr-->
        <nav class="user_lists">
            <a target="_top" href="<?php if(empty($user)) echo '/user/login.html?fwd='; ?>/user/games.html" class="block_bg">
                <i class="icon i_list1"></i>
                <span>最近在玩</span>
                <span class="icon i_go"></span>
            </a>
            <a target="_top" href="<?php if(empty($user)) echo '/user/login.html?fwd='; ?>/user/favorites.html" class="block_bg">
                <i class="icon i_list2"></i>
                <span>我的收藏</span>
                <!--<sup class="sup_number">12</sup>-->
                <span class="icon i_go"></span>
            </a>
            <a target="_top" href="<?php if(empty($user)) echo '/user/login.html?fwd='; ?>/pay/index.html" class="block_bg">
                <i class="icon i_list3"></i>
                <span>充值中心</span>
                <span class="icon i_go"></span>
            </a>
            <a target="_top" href="/game/center.html" class="block_bg">
                <i class="icon i_list4"></i>
                <span>游戏大厅</span>
                <span class="icon i_go"></span>
            </a>
            <a href="javascript:void(0)" class="block_bg">
                <i class="icon i_list5"></i>
                <span>我的积分</span>
                <span class="icon i_go"></span>
            </a>
            <a target="_top" href="<?php if(empty($user)) echo '/user/login.html?fwd='; ?>/user/fcm.html" class="block_bg">
                <i class="icon i_list6"></i>
                <span>防沉迷验证</span>
                <span class="icon i_go"></span>
            </a>
        </nav>
        <!--nav.user_lists 用户信息分类列表 end-->
        <div class="footer_padding" style="height:57px;"></div>
    </div>
    <!--div.z_min 内容区域 end-->
</div>
<!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script>$('#footer a:eq(4)').attr('id', 'footer_nav_active');</script>
</body>
</html>