<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>登录 - 久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/login.css"/>
</head>
<body class="bg00">
<!--div.container 总外框  start-->
<div class="z_container bg02">
    <header class="z_header">
        <a id="return_url" target="_top" href="<?=$fwd ? $fwd : '/game/index.html'?>"></a>
        <span>登录到久乐游戏</span>
    </header>

    <!--div.z_min 内容区域 statr-->
    <div class="z_main" data-role="conent">
        <form class="user_form">
            <input type="text" id="username" placeholder="账号"/>
            <input type="password" id="password" placeholder="密码"/>
            <div>
            <a href="javascript:void(0)" class="login_btn" style="float: right">登录</a>
            <a target="_top" href="/user/register.html<?=$fwd ? '?fwd='.urlencode($fwd) : ''?>" class="register_btn" style="float: left">注册</a>
            </div>
        </form>
        <section class="login_nav">
            <h3>
                <span class="line_through"></span>
                <span class="center_word">快速登录:</span>
                <span class="line_through"></span>
            </h3>
            <?if($_SERVER['SERVER_NAME']=='h5.zyttx.com'):?>
            <nav>
                <span class="split_h"></span>
                <a href="javascript:void(0)" class="left_btn" id="wx_login">
                    <i class="logos weixin_img"></i><span>微信登录</span>
                </a>
                <a target="_top" href="/user/qqlogin.html<?=$fwd ? '?fwd='.urlencode($fwd) : ''?>" class="right_btn" style="text-indent:50px">
                    <i class="logos qq_img"></i><span>QQ登录</span>
                </a>
            </nav>
            <?php endif;?>
        </section>
        
        <section class="bottom_btns">
            <div class="box1">
                <i id="login_auto" class="i_check"></i>
                <label for="login_auto">下次自动登录</label>
            </div>
    		<div class="box2">
<!--            	<a target="_top" href="/user/register.html--><?//=$fwd ? '?fwd='.urlencode($fwd) : ''?><!--" class="btn_green2">注册账号</a>-->
    		</div>
<!--    		<div class="box3">-->
<!--            	<a target="_top" href="/user/forget.html">找回密码</a>-->
<!--    		</div>-->
        </section>
        <div class="footer_padding"></div>
    </div>
    <!--div.z_min 内容区域 end-->
</div>
<!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script>
$('#footer a:eq(4)').attr('id', 'footer_nav_active');
$(function(){
	$('.user_form input').focus(function(){
		$('#footer').hide();
	}).blur(function(){
		$('#footer').show();
	});

	var remember = 0;
	$(".i_check").on("tap", function(){
        $(this).toggleClass("selected");
        remember = $(this).hasClass("selected") ? 1 : 0;
    });
    $('label[for]').on('tap', function(){
        $(this).prev().trigger('tap');
    });

    var fwd = '<?=$fwd?>';
	var loading = false;
	$('a.login_btn').on('tap', function(){
		if( loading ) return false;
		var u = $.trim($('#username').val());
		if( u == '' ) {
			alert('请输入你的用户名！');
			$('#username').focus();
			return false;
		}
		var p = $.trim($('#password').val());
		if( p == '' ) {
			alert('请输入你的密码！');
			$('#password').focus();
			return false;
		}
		loading = true;
		$.ajax({
	        type: 'POST',
	        url: '/user/ajaxlogin.html',
	        data: 'username='+u+'&password='+p+'&remember='+remember,
	        dataType: 'json',
	        success: function(msg){
	        	loading = false;
	            if( msg.msg != 'success' ) {
	                if( msg.fwd != '' ) {
		                if( confirm(msg.msg) )
			                location.href = msg.fwd;
		            } else {
		            	alert(msg.msg);
		            }
	            } else {
		            if( fwd != '' ) {
		            	location.href = fwd;
		            } else if( msg.fwd != '' ) {
		                location.href = msg.fwd;
		            } else {
	                	location.href = $('#return_url').attr('href');
		            }
	            }
	        },
	        error: function(){
	        	loading = false;
	        	alert('网络连接失败！');
	        }
	    });
	});

	$('#wx_login').on('tap', function(){
	    alert('正在开发，敬请期待！');
	    return false;
		if( navigator.userAgent.indexOf('MicroMessenger') == -1 ) {
			alert('请在微信中打开此页面，再使用微信登录功能！');
		} else {
			location.href = '/user/wxlogin.html<?=$fwd ? '?fwd='.urlencode($fwd) : ''?>';
		}
	});

	var err = '<?=$err?>';
	if( err != '' ) alert(err);
});
</script>
</body>
</html>