<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta charset="UTF-8">
<meta name="generator" content="namiyx.dxj">
<meta content="yes" name="apple-touch-fullscreen"><meta content="yes" name="full-screen">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"/>
<title></title>
</head>
<body>
<script>
	history.go(-2);
</script>
</body>
</html>