<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<title>修改密码 - 个人资料 - 久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/user_password.css"/>
</head>
<body class="bg02">
<!--div.container 总外框  start-->
<div class="z_container" >
    <header class="z_header block_bg">
        <a target="_top" href="/user/edit.html"></a><span>修改密码</span>
    </header>

    <!--div.z_min 内容区域 statr-->
    <div class="z_main" data-role="conent">
        <form class="user_form">
            <input class="text" type="password" placeholder="旧密码" id="oldpwd"/>
            <input class="text" type="password" placeholder="新密码" id="newpwd"/>
            <input class="text" type="password" placeholder="确认新密码" id="re_pwd"/>
            <a class="login_btn" id="save" href="javascript:void(0)">确认</a>
            <div class="service">
                <i class="i_qq"></i>客服QQ:<?=$qq_group?>
            </div>
        </form>
        <div class="footer_padding"></div>
    </div>
    <!--div.z_min 内容区域 end-->
</div>
<!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script>
$('#footer a:eq(4)').attr('id', 'footer_nav_active');
$(function(){
    /**修改默认输入框失去焦点事件样式*/
    $(".user_form input").blur(function(){
    	var _t = $(this);
        var v = $.trim(_t.val());
        if(v != ""){
            _t.css("color","#fff");
        } else {
        	_t.css("color","#3c555e");
        }
    	$('#footer').show();
    }).focus(function(){
        $(this).css("color","#fff");
    	$('#footer').hide();
    });

    var loading = false;
    $('#save').on('tap', function(){
        if( loading ) return false;
        var o = $.trim($('#oldpwd').val());
        var n = $.trim($('#newpwd').val());
        var r = $.trim($('#re_pwd').val());
        if( o.length < 6 ) {
            alert('请输入你的旧密码！');
            $('#oldpwd').focus();
            return false;
        }
        if( n.length < 6 ) {
            alert('为了你的账号安全，请设置6位以上的密码！');
            $('#newpwd').focus();
            return false;
        }
        if( n == o ) {
        	alert('新密码必须与旧密码不同！');
            $('#newpwd').focus();
            return false;
        }
        if( n != r ) {
            alert('确认密码与新密码不符！');
            $('#re_pwd').focus();
            return false;
        }
        loading = true;
        $.ajax({
            url: '/user/password.html',
            type: 'POST',
            dataType: 'json',
            data: 'oldpwd='+o+'&newpwd='+n+'&re_pwd='+r,
            success: function(msg){
            	loading = false;
                alert(msg.msg);
                if( msg.fwd ) location.href = msg.fwd;
            },
            error: function(){
                loading = false;
                alert('网络连接失败！');
            }
        });
    });
});
</script>
</body>
</html>