<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>我的推广 - 久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/my_favs.css"/>
<link rel="stylesheet" href="/styles/pay_list.css"/>
    <style>
        .login_btn {
            display: block;
            width: 50%;
            height: 45px;
            line-height: 45px;
            background-color: #29ba67;
            color: #ffffff;
            border: 0;
            border-radius: 2px;
            font-size: 24px;
            font-weight: 100;
            text-align: center;
            -webkit-box-shadow: 0 0 rgba(255, 0, 0, 0);
            box-shadow: 0 0 rgba(255, 0, 0, 0);
            margin: 27px auto 0;
            border-radius: 5px;
        }
        ui,li {
            list-style: none;
        }
        #news{
            height: 24px;
            overflow: hidden;
            /*border: solid 1px;*/
            text-align: center;
        }
    </style>
</head>
<body class="bg00">
<div data-role="page" class="z_container bg01">
    <div class="main">
        <header  class="z_header">
            <a target="_top" href="/user/index.html"></a>推广赚钱
        </header>

        <section style="padding: 10px;font-size: large;">
               推广说明<br/>
                <div style="font-size: small;padding: 10px;color: #bbbbbb">
                    您的好友通过你的推广链接注册成功后，成为你的下线，他充值你就有20%的提成!
                </div>
            <div>
                推广宣传语
                <div style="font-size: small;padding: 10px">
                    <textarea id="mytext" style="width: 100%;height: 80px;">我在玩最新版GM手游,不花一分钱上线送满级VIP+无限元宝,不花一分钱体验GM牛逼特权,道具装备随便刷一切,游戏下载地址：<?="http://".$_SERVER['HTTP_HOST'].'/user/register.html?fwd=/user/index&player_channel='.$_SESSION['user_id']?>
                    </textarea>
                    <br/>
<!--                    <button id="copy_input">复制</button>-->
                    <button onClick="copyUrl()" class="login_btn" id="save" id="copy_input"><image src="/images/playerchannel/share.png" style="width: 20px;height: 20px;"></image>复制推广语</button>
                </div>
            </div>
            <!--            <div>-->
<!--                操作方法:<br/>-->
<!--                复制以下信息<br/>-->
<!--                <div style="font-size: small">-->
<!--                   久乐游戏-转发就能赚钱，每天五分钟，轻松月入上万   --><?//="http://".$_SERVER['HTTP_HOST'].'/user/register.html?fwd=user/index&player_channel='.$_SESSION['user_id']?>
<!--                </div>-->
<!--                1.作为QQ签名<br/>-->
<!--                2.发到QQ群或微信群<br/>-->
<!--                3.作为微信签名<br/>-->
<!--            </div>-->
            <div id="news">
                <ul>
                    <li>账号	67***170邀请	63***10充值100获得收益20</li>
                    <li>账号	34****280邀请94***525充值150	获得收益	30</li>
                    <li>账号	cui****hao邀请56***780充值55	获得收益	11</li>
                    <li>账号	534***23邀请	ro***gjb充值	1000获得收益	200</li>
                    <li>账号	s13***146邀请429***93充值2500获得收益	500</li>
                    <li>账号	189***25邀请	zer***o04充值3000获得收益	600</li>
                    <li>账号	wzy***67邀请	a42***693充值310	获得收益	62</li>
                    <li>账号	764***09邀请	zer***o03充值450	获得收益	90</li>
                    <li>账号	sta***ngna邀请809***1充值188	获得收益	37.6</li>
                    <li>账号	980***900邀请chin***n123	充值	1500获得收益	300</li>
                    <li>账号	star***u*in	邀请	a28***838充值1650获得收益	330</li>
                    <li>账号	378***46邀请	556***3645充值6750获得收益1350</li>
                    <li>账号	ps***990邀请	4923***467充值3340获得收益668</li>
                    <li>账号	86***472邀请	2393***50充值486	获得收益	97.2</li>
                    <li>账号	12***043邀请	s268***650充值1860获得收益372</li>
                    <li>账号	a4***00	邀请	l26***650充值2890获得收益	578</li>
                    <li>账号	132***5955邀请348***0789	充值	123	获得收益	24.6</li>
                    <li>账号	754***80邀请	755***048充值6811获得收益	1362.2</li>
                    <li>账号	1261***38邀请ze***ro02充值1231获得收益246.2</li>
                    <li>账号	83***388邀请	120***859充值2322获得收益	464.4</li>
                    <li>账号	a57***51邀请	591***14充值	11582获得收益2316.4</li>
                    <li>账号	435***030邀请977***681充值2876获得收益575.2</li>
                    <li>账号	180***4405邀请zerWW***o01充值3511获得收益	702.2</li>
                    <li>账号	103***313邀请719***47充值608	获得收益	121.6</li>
                    <li>账号	589***235邀请iao***na04充值758获得收益151.6</li>
                    <li>账号	168***604邀请828***234充值696获得收益	139.2</li>
                    <li>账号	162***761邀请347***84充值10获得收益2</li>
                    <li>账号	769***007邀请5070***67充值55获得收益11</li>
                    <li>账号	a10***75邀请	7371***66充值80获得收益16</li>
                    <li>账号	a10***8926邀请lin0***313	充值	166	获得收益	33.2</li>
                    <li>账号	151***5277邀请357***9充值322	获得收益	64.4</li>
                    <li>账号	Kelly***251邀请1836***2充值1280获得收益256</li>
                    <li>账号	344***51邀请	6970***74充值1000获得收益	200</li>
                    <li>账号	17***99	邀请	761***33充值	998获得收益199.6</li>
                    <li>账号	az***ai1邀请	170***26充值	648获得收益129.6</li>
                    <li>账号	nht***011邀请181***89充值98获得收益19.6</li>
                    <li>账号	246***68邀请	176***35充值	188获得收益37.6</li>
                    <li>账号	ti***yy	邀请	56***455充值	1040获得收益208</li>
                    <li>账号	miu***071邀请823***905充值66获得收益13.2</li>
                    <li>账号	ccv***ao88邀请83750***46充值36获得收益7.2</li>
                    <li>账号	681***68邀请	54515***49充值1869获得收益373.8</li>
                    <li>账号	575***80邀请	xue***521充值30获得收益6</li>
                    <li>账号	368***47邀请	1233***3充值	10获得收益2</li>
                    <li>账号	Pf1***789邀请296***36充值66获得收益13.2</li>
                    <li>账号	400***30邀请	703***02充值	25获得收益5</li>
                    <li>账号	763***54邀请	617***01充值	90获得收益18</li>
                    <li>账号	615***66邀请	891***12充值	18990获得收益3798</li>
                    <li>账号	86***52	邀请	wy33***7815充值10369	获得收益	2073.8</li>
                    <li>账号	14***804邀请	976***5103充值7785获得收益1557</li>
                </ul>
            </div>
            <div class="pay_list gift_logs">
                <ul class="list_header">
                    <li>
                        <span>注册时间</span>
                        <span class="bold col-2">用户名</span>
                        <span class="col-3">获得收益</span>
                    </li>
                </ul>
                <ul class="list_body">
                    <li>
                        <a id="show_more" href="javascript:void(0)"><span>显示跟多 &gt;</span></a>
                    </li>
                </ul>
            </div>
        </section>

    </div>
    <div class="footer_padding"></div>
</div>
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/js/jquery-zclip/jquery.zclip.js"></script>
<script>
$('#footer a:eq(4)').attr('id', 'footer_nav_active');
function copyUrl() {
    var Url2 = document.getElementById("mytext");
    Url2.select(); // 选择对象
    document.execCommand("Copy"); // 执行浏览器复制命令
    alert("已复制好，可贴粘。");
}
$(function(){
	$('.i_delete').parent().on('tap', function(){
		$('.i_close').toggleClass('none');
	});

	var loading = false;
	var timeout = true;
	$('.i_close').on('vmouseup', function(){
		if( loading || ! timeout ) return false;
		loading = true;
		timeout = false;
		setTimeout(function(){
			timeout = true;
		}, 1000);
		var _t = $(this);
		var gid = _t.attr('data-gid');
		$.ajax({
			url: '/user/delfavorite.html',
			type: 'POST',
			dataType: 'text',
			data: 'game_id='+gid,
			success: function(msg){
				if( msg != 'success' ) {
					alert(msg);
					loading = false;
				} else {
					_t.parent().fadeOut('fast', function(){
						_t.parent().remove();
						loading = false;
						if( $('ul.game_list > li').length < 1 ) location.reload();
					});
				}
			},
			error: function(){
				loading = false;
				alert('网络连接失败，请重试！');
			}
		});
	});
	//显示数据
    var pn = 0;
    var limit = 8;
    var nomore = false;
    var loading = false;
    function morePayLogs()
    {
        if( loading || nomore ) return false;
        ++pn;
        var send = 'pn='+pn+'&limit='+limit;
        loading = true;
        $.ajax({
            type: 'GET',
            url: '/user/playerchannellist.html',
            data: send,
            dataType: 'html',
            success: function(msg){
                if( $(msg).length < 1 ) {
                    $('#show_more span').html('没有更多了...');
                    nomore = true;
                } else {
                    $(msg).insertBefore($('#show_more').parent());
                    if( $(msg).length < limit) {
                        $('#show_more span').html('没有更多了...');
                        nomore = true;
                    }
                }
                loading = false;
            },
            error: function(){
                loading = false;
            }
        });
    }
    morePayLogs();
    $('#show_more').on('click', morePayLogs);


});
</script>
<?php
$player_channel_addr="http://".$_SERVER['HTTP_HOST'].'/user/register.html?fwd=user/index&player_channel='.$_SESSION['user_id'];
?>
<script>
    $('#qrcode_player_channel').qrcode({
        text:"<?=$player_channel_addr?>",
        width: 160, //宽度
        height:160, //高度
        background: "#ffffff",
        correctLevel: 0,//纠错等级
    });
    $(function() {
        var $this = $("#news");
        var scrollTimer;
        $this.hover(function() {
            clearInterval(scrollTimer);
        }, function() {
            scrollTimer = setInterval(function() {
                scrollNews($this);
            }, 2000);
        }).trigger("mouseleave");

        function scrollNews(obj) {
            var $self = obj.find("ul");
            var lineHeight = $self.find("li:first").height();

            $self.animate({
                "marginTop": -lineHeight + "px"
            }, 500, function() {
                $self.css({
                    marginTop: 0
                }).find("li:first").appendTo($self);
            })
        }
    })
</script>
</body>
</html>