<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>我的推广 - 久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/my_favs.css"/>
<link rel="stylesheet" href="/styles/pay_list.css"/>
    <style>
        .login_btn {
            display: block;
            width: 50%;
            height: 45px;
            line-height: 45px;
            background-color: #29ba67;
            color: #ffffff;
            border: 0;
            border-radius: 2px;
            font-size: 24px;
            font-weight: 100;
            text-align: center;
            -webkit-box-shadow: 0 0 rgba(255, 0, 0, 0);
            box-shadow: 0 0 rgba(255, 0, 0, 0);
            margin: 27px auto 0;
            border-radius: 5px;
        }
    </style>
</head>
<body class="bg00">
<div data-role="page" class="z_container bg01">
    <div class="main">
        <header  class="z_header">
            <a target="_top" href="/user/index.html"></a>推广赚钱
        </header>

        <section style="padding: 10px;font-size: large;">
               推广说明<br/>
                <div style="font-size: small;padding: 10px;color: #bbbbbb">
                    您的好友通过你的推广链接注册成功后，成为你的下线，他充值你就有20%的提成!
                </div>
            <div>
                推广宣传语
                <div style="font-size: small;padding: 10px">
                    <textarea id="mytext" style="width: 100%;height: 80px;">我在玩最新版GM手游,不花一分钱上线送满级VIP+无限元宝,不花一分钱体验GM牛逼特权,道具装备随便刷一切,游戏下载地址：<?="http://".$_SERVER['HTTP_HOST'].'/user/register.html?fwd=/user/index&player_channel='.$_SESSION['user_id']?>
                    </textarea>
                    <br/>
<!--                    <button id="copy_input">复制</button>-->
                    <button onClick="copyUrl()" class="login_btn" id="save" id="copy_input"><image src="/images/playerchannel/share.png" style="width: 20px;height: 20px;"></image>复制推广语</button>
                </div>
            </div>
            <!--            <div>-->
<!--                操作方法:<br/>-->
<!--                复制以下信息<br/>-->
<!--                <div style="font-size: small">-->
<!--                   久乐游戏-转发就能赚钱，每天五分钟，轻松月入上万   --><?//="http://".$_SERVER['HTTP_HOST'].'/user/register.html?fwd=user/index&player_channel='.$_SESSION['user_id']?>
<!--                </div>-->
<!--                1.作为QQ签名<br/>-->
<!--                2.发到QQ群或微信群<br/>-->
<!--                3.作为微信签名<br/>-->
<!--            </div>-->
            我的下线
            <div class="pay_list gift_logs">
                <ul class="list_header">
                    <li>
                        <span>注册时间</span>
                        <span class="bold col-2">用户名</span>
                        <span class="col-3">获得收益</span>
                    </li>
                </ul>
                <ul class="list_body">
                    <li>
                        <a id="show_more" href="javascript:void(0)"><span>显示跟多 &gt;</span></a>
                    </li>
                </ul>
            </div>
        </section>

    </div>
    <div class="footer_padding"></div>
</div>
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/js/jquery-zclip/jquery.zclip.js"></script>
<script>
$('#footer a:eq(4)').attr('id', 'footer_nav_active');
function copyUrl() {
    var Url2 = document.getElementById("mytext");
    Url2.select(); // 选择对象
    document.execCommand("Copy"); // 执行浏览器复制命令
    alert("已复制好，可贴粘。");
}
$(function(){
	$('.i_delete').parent().on('tap', function(){
		$('.i_close').toggleClass('none');
	});

	var loading = false;
	var timeout = true;
	$('.i_close').on('vmouseup', function(){
		if( loading || ! timeout ) return false;
		loading = true;
		timeout = false;
		setTimeout(function(){
			timeout = true;
		}, 1000);
		var _t = $(this);
		var gid = _t.attr('data-gid');
		$.ajax({
			url: '/user/delfavorite.html',
			type: 'POST',
			dataType: 'text',
			data: 'game_id='+gid,
			success: function(msg){
				if( msg != 'success' ) {
					alert(msg);
					loading = false;
				} else {
					_t.parent().fadeOut('fast', function(){
						_t.parent().remove();
						loading = false;
						if( $('ul.game_list > li').length < 1 ) location.reload();
					});
				}
			},
			error: function(){
				loading = false;
				alert('网络连接失败，请重试！');
			}
		});
	});
	//显示数据
    var pn = 0;
    var limit = 8;
    var nomore = false;
    var loading = false;
    function morePayLogs()
    {
        if( loading || nomore ) return false;
        ++pn;
        var send = 'pn='+pn+'&limit='+limit;
        loading = true;
        $.ajax({
            type: 'GET',
            url: '/user/playerchannellist.html',
            data: send,
            dataType: 'html',
            success: function(msg){
                if( $(msg).length < 1 ) {
                    $('#show_more span').html('没有更多了...');
                    nomore = true;
                } else {
                    $(msg).insertBefore($('#show_more').parent());
                    if( $(msg).length < limit) {
                        $('#show_more span').html('没有更多了...');
                        nomore = true;
                    }
                }
                loading = false;
            },
            error: function(){
                loading = false;
            }
        });
    }
    morePayLogs();
    $('#show_more').on('click', morePayLogs);

});
</script>
<?php
$player_channel_addr="http://".$_SERVER['HTTP_HOST'].'/user/register.html?fwd=user/index&player_channel='.$_SESSION['user_id'];
?>
<script>
    $('#qrcode_player_channel').qrcode({
        text:"<?=$player_channel_addr?>",
        width: 160, //宽度
        height:160, //高度
        background: "#ffffff",
        correctLevel: 0,//纠错等级
    });
</script>
</body>
</html>