<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<title>久乐游戏微信公众号</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/user_share.css"/>
</head>
<body class="bg00">
<!--div.container 总外框  start-->
<div class="z_container bg02" >
    <header class="z_header block_bg">
        <a href="javascript:void(0)"></a><span>分享</span>
    </header>

    <!--div.z_min 内容区域 statr-->
    <div class="z_main">
        <figure>
            <img src="/public/images/2wm.jpg" width="235" height="auto"/>
        </figure>
        <p>扫二维码关注 <span class="green">久乐游戏</span> 公众号</p>
        <p>分享到朋友圈 有小惊喜哟~</p>
        <div class="footer_padding"></div>
    </div>
    <!--div.z_min 内容区域 end-->

</div>
<!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
</body>
</html>