<!--footer 底部 start-->
<footer id="footer" class="z_footer">
    <nav>
        <a target="_top" href="/game/index.html" title="久乐H5游戏首页">
            <i class="icons i_ft01"></i>
            <span>首页</span>
        </a>
        <a target="_top" href="/info/index.html" title="久乐H5游戏资讯">
            <i class="icons i_ft02"></i>
            <span>活动</span>
        </a>
        <a target="_top" href="/game/center.html" title="久乐H5游戏大厅、游戏中心">
            <i class="icons i_ft03"></i>
            <span>游戏</span>
        </a>
        <a target="_top" href="/activity/giftbag.html" title="久乐H5游戏活动、礼包、兑换码">
            <i class="icons i_ft04"></i>
            <span>礼包</span>
        </a>
        <a target="_top" href="/user/index.html" title="我的久乐游戏">
            <i class="icons i_ft05"></i>
            <span>我的</span>
        </a>
    </nav>
</footer>
<!--footer 底部  end-->
<div style="width:0;height:0;overflow:hidden;"><script src="http://s95.cnzz.com/z_stat.php?id=1256660450&web_id=1256660450"></script></div>
