<!--footer 底部 start-->
<footer id="footer" class="z_footer">
    <nav>
        <a target="_top" href="/game/index.html" title="久乐H5游戏首页">
            <i class="icons i_ft01"></i>
            <span>首页</span>
        </a>
        <a target="_top" href="/info/index.html" title="久乐H5游戏资讯">
            <i class="icons i_ft02"></i>
            <span>活动</span>
        </a>
        <a target="_top" href="/game/center.html" title="久乐H5游戏大厅、游戏中心">
            <i class="icons i_ft03"></i>
            <span>游戏</span>
        </a>
        <a target="_top" href="/activity/giftbag.html" title="久乐H5游戏活动、礼包、兑换码">
            <i class="icons i_ft04"></i>
            <span>礼包</span>
        </a>
        <a target="_top" href="/user/index.html" title="我的久乐游戏">
            <i class="icons i_ft05"></i>
            <span>我的</span>
        </a>
    </nav>
</footer>
<div id="qrcode" class="qrcode_image"/>
<!--二维码-->
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.qrcode.min.js"></script>

<!--<div class="qrcode_image">-->
<!--        <img src="/qrcode/game.html?addr=--><?//="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']?><!--">-->
<!--</div>-->
<?php
        //第一次缓存链接
        $addr="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $session=Yaf_Session::getInstance();
        if($session->has('url')){
	        $addr=$session->get('url');
        }else {
            $session->set('url',$addr);
        }
?>
<script>
    $('#qrcode').qrcode("<?=$addr?>");
</script>

