<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta charset="UTF-8">
<meta name="generator" content="namiyx.dxj">
<meta content="yes" name="apple-touch-fullscreen"><meta content="yes" name="full-screen">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
<meta name="keywords" content="H5 HTML5 H5游戏 HTML5游戏 小游戏 手机游戏 网页游戏 在线游戏 点击即玩 久乐游戏 久乐H5 H5平台">
<meta name="description" content="久乐游戏是一个行业领先的H5在线游戏平台，玩游戏不再苦苦的等待下载，点击即玩。">
<title>页面未找到 - <?=$sitename?>，H5在线游戏平台</title>
<link rel="stylesheet" href="/public/styles/base.css">
<style>
img.error404{border:0; height:100%; width:100%}
a.return_to_game{display:block; height:6.866%; width:44.219%; position:absolute; left:28.594%; top:61.62%}
.z_footer{position:fixed; bottom:0; width:100%; border:0; background-color:#1F252D; padding:5px 0; height:44px; z-index:1000}
</style>
</head>
<body>
    <img class="error404" src="/images/error/404.jpg">
    <a class="return_to_game" href="/game/index.html"></a>
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</body>
</html>