<noscript>
<!-- Show a notification if the user has disabled javascript -->
<div class="notification error png_bg">
  <div> Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
    Download From <a href="http://www.exet.tk">exet.tk</a></div>
</div>
</noscript>

<!-- Page Head -->
<h2>Welcome</h2>
<p id="page-intro">开发者中心后台管理！</p>
<h4></h4>
<div class="clear"></div>
<!-- End .clear -->
