<div class="content-box">
  <div class="content-box-header">
    <h3>警告：<small>（<?=$time?>秒后跳转）</small></h3>
  </div>
  <!-- End .content-box-header -->
  <div class="content-box-content">
    <div class="tab-content default-tab">
        <div class="notification attention png_bg"> <a href="#" class="close"><img src="/admin/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
            <div><?=$msg?>&nbsp;&nbsp;&nbsp;<a id="back_now" href="#">立即返回</a></div>
        </div>
    </div>
    <!-- End #tab3 -->
  </div>
  <!-- End .content-box-content -->
</div>

<script>
var time = parseInt('<?=$time?>');
if( isNaN(time) || time < 1 ) {
	time = 3;
}
time *= 1000;
var url = '<?=$url?>';
var func = function(){
	if( url == '-1' )
		history.go(-1);
	else
		location.href = url;
};
$('#back_now').on('click', func);
setTimeout(func, time);
</script>
