<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>久乐H5游戏联运平台-最好的H5游戏联运平台！</title>
    <!--                       CSS                       -->
    <!-- Reset Stylesheet -->
    <link rel="stylesheet" href="/admin/css/reset.css" type="text/css" media="screen" />
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="/admin/css/style.css" type="text/css" media="screen" />
    <!-- Invalid Stylesheet. This makes stuff look pretty. Remove it if you want the CSS completely valid -->
    <link rel="stylesheet" href="/admin/css/invalid.css" type="text/css" media="screen" />
    <!--                       Javascripts                       -->
    <!-- jQuery -->
    <script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
    <!-- jQuery Configuration -->
    <script type="text/javascript" src="/admin/js/simpla.jquery.configuration.js"></script>
</head>
    <body>
    <div id="body-wrapper">
        <div id="main-content">
    <!-- Page Head -->
    <h2>公告详情</h2>
<!--    <p id="page-intro">这里是系统的简要统计信息，当前在线人数为当前的活跃链接数，存在一点误差！</p>-->
    <div class="clear"></div>
    <!-- End .clear -->
    <div class="content-box">
      <div class="content-box-header">
        <h3><?=$artic['title']?><small></small></h3>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
          <h4><?=$artic['content']?></h4>
        </div>
        <!-- End #tab3 -->
      </div>
            <!-- End #tab3 -->
        </div>
    <!-- End .content-box -->
    <div class="clear"></div>
        </div>
    </body>

