<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>久乐H5游戏联运平台-最好的H5游戏联运平台！</title>
</head>
<frameset cols="240,*" frameborder="no">
	<frame src="/admin/index/left" frameborder="0" scrolling="auto" noresize="noresize" />
	<frame src="/admin/index/right" frameborder="0" scrolling="auto" noresize="noresize" id="right" />
</frameset>
</html>