    <noscript>
    <!-- Show a notification if the user has disabled javascript -->
    <div class="notification error png_bg">
      <div> Javascript is disabled or is not supported by your browser. Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a> Javascript to navigate the interface properly.
        Download From <a href="http://www.exet.tk">exet.tk</a></div>
    </div>
    </noscript>
    
    <!-- Page Head -->
    <h2>个人中心</h2>
<!--    <p id="page-intro">这里是系统的简要统计信息，当前在线人数为当前的活跃链接数，存在一点误差！</p>-->
    <div class="clear"></div>
    <!-- End .clear -->
    
    <div class="content-box column-left">
      <div class="content-box-header">
        <h3>24小时活跃链接数<small></small></h3>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
          <h4><?=$count?></h4>
        </div>
        <!-- End #tab3 -->
      </div>
      <!-- End .content-box-content -->
        <div class="content-box-header">
            <h3>您的推广链接<small></small></h3>
        </div>
        <!-- End .content-box-header -->
        <div class="content-box-content">
            <div class="tab-content default-tab">
                <h4><a target="_blank" href="<?='http://h5.zyttx.com/?user='.$_SESSION['admin_id']?>"><?='http://h5.zyttx.com/?user='.$_SESSION['admin_id']?></a> </h4>
            </div>
            <!-- End #tab3 -->
        </div>
        <div class="content-box-header">
            <h3>安卓盒子链接<small></small></h3>
        </div>
        <!-- End .content-box-header -->
        <div class="content-box-content">
            <div class="tab-content default-tab">
                <h4>
                    <?php if(file_exists('/www/wwwroot/xgame.zyttx.com/apk/'.$_SESSION['admin_id'].'.apk')):?>
                        <a target="_blank" href="<?='http://xgame.zyttx.com/apk/'.$_SESSION['admin_id'].'.apk'?>"><?='http://xgame.zyttx.com/apk/'.$_SESSION['admin_id'].'.apk'?></a>
                    <?php else:?>
                        <a href="/admin/admin/apk">您还没有渠道apk链接,点击生成!</a>
                    <?php endif;?>
                </h4>
            </div>
            <!-- End #tab3 -->
        </div>
    </div>
    <!-- End .content-box -->
<!--    <div class="content-box column-right">-->
<!--      <div class="content-box-header">-->
<!--        <!-- Add the class "closed" to the Content box header to have it closed by default -->
<!--        <h3>缓存使用情况</h3>-->
<!--      </div>-->
<!--      <!-- End .content-box-header -->
<!--      <div class="content-box-content">-->
<!--        <div class="tab-content default-tab">-->
<!--          <p>已使用：--><?//=$stat['bytes']?><!--</p>-->
<!--          <p>总&nbsp;&nbsp;&nbsp;计：--><?//=$stat['limit_maxbytes']?><!--</p>-->
<!--          <p>使用率：--><?//=$stat['used_percent']?><!--</p>-->
<!--        </div>-->
<!--        <!-- End #tab3 -->
<!--      </div>-->
<!--      <!-- End .content-box-content -->
<!--    </div>-->
    <!-- End .content-box -->
    <div class="clear"></div>
    <script type="text/javascript" src="/admin/js/common.js"></script>

