<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>客服中心</title>
    <link rel="stylesheet" href="/public/styles/base.css"/>
    <link rel="stylesheet" href="/styles/pay_edit.css"/>
</head>
<body style="background-color:#ffffff">
<!--div.container 总外框  start-->
<div>
   <h1>
       <span>客服QQ:<?=$info['service_qq'];?></span>
   </h1>
    <h1>
        <span>群:<?=$info['service_qq2'];?></span>
    </h1>
</div>
<!--div.container 总外框  end-->
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
</body>
</html>