<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="keywords" content="H5 HTML5 H5游戏 HTML5游戏 小游戏 手机游戏 网页游戏 在线游戏 点击即玩 久乐游戏 久乐H5 H5平台">
<meta name="description" content="久乐游戏是一个行业领先的H5在线游戏平台，玩游戏不再苦苦的等待下载，点击即玩。">
<title>久乐游戏大厅 - H5在线游戏平台点击即玩</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/game_center.css"/>
</head>
<body class="bg00">
    <!--div.container 总外框  start-->
    <div data-role="page" class="z_container bg01">
        <!--div.z_min 内容区域 statr-->
        <div class="z_main">
            <header class="z_header">
                <a href="/game/index.html"></a><sapn>游戏大厅</sapn>
            </header>
            <section class="classify">
                <h3 class="block_bg"> <i class="i_game2"></i>久乐分类 </h3>
                <nav class="block_bg nav_classify">
                    <a href="/game/type.html?tc=精品推荐"><img src="/images/game_center/game_03.jpg" alt="精品推荐" width="100%" height="auto"></a>
                    <a href="/game/type.html?tc=独家首发"><img src="/images/game_center/game_05.jpg" alt="独家首发" width="100%" height="auto"/></a>
                    <a href="/game/type.html?tc=满V游戏"><img src="/images/game_center/game_07.jpg" alt="满V游戏" width="100%" height="auto"/></a>
                    <a href="/game/type.html?tc=BT游戏"><img src="/images/game_center/game_11.jpg" alt="BT游戏" width="100%" height="auto"/></a>
                    <a href="/game/type.html?tc=GM游戏"><img src="/images/game_center/game_13.jpg" alt="GM游戏" width="100%" height="auto"/></a>
                </nav>
            </section>
            <!--div.game_list 游戏列表  start-->
            <section class="classify">
                <h3 class="block_bg"> <i class="i_types"></i>常见类型 </h3>
                <nav class="types_nav">
                    <div>
                        <a href="/game/type.html?tc=角色扮演">
                            <i><img src="/images/game_center/1.png" alt="角色扮演" width="100%" height="auto"/></i>
                            <span>角色扮演</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=动作过关">
                            <i><img src="/images/game_center/2.png" alt="动作过关" width="100%" height="auto"/></i>
                            <span>动作过关</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=休闲娱乐">
                            <i><img src="/images/game_center/3.png" alt="休闲娱乐" width="100%" height="auto"/></i>
                            <span>休闲娱乐</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=街机童年">
                            <i><img src="/images/game_center/9.png" alt="街机童年" width="100%" height="auto"/></i>
                            <span>街机童年</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=竞速狂飙">
                            <i><img src="/images/game_center/10.png" alt="竞速狂飙" width="100%" height="auto"/></i>
                            <span>竞速狂飙</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=卡牌回合">
                            <i><img src="/images/game_center/8.png" alt="卡牌回合" width="100%" height="auto"/></i>
                            <span>卡牌回合</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=体育竞技">
                            <i><img src="/images/game_center/4.png" alt="体育竞技" width="100%" height="auto"/></i>
                            <span>体育竞技</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=解密探险">
                            <i><img src="/images/game_center/5.png" alt="解密冒险" width="100%" height="auto"/></i>
                            <span>解密探险</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=放置挂机">
                            <i><img src="/images/game_center/6.png" alt="放置挂机" width="100%" height="auto"/></i>
                            <span>放置挂机</span>
                        </a>
                    </div>
                    <div>
                        <a href="/game/type.html?tc=音乐舞蹈">
                            <i><img src="/images/game_center/7.png" alt="音乐舞蹈" width="100%" height="auto"/></i>
                            <span>音乐舞蹈</span>
                        </a>
                    </div>
                    <div class="green">
                        <a href="/game/type.html?tc=全部分类">
                            <i><img src="/images/game_center/other.png" width="100%" height="auto"/></i>
                            <span>全部</span>
                        </a>
                    </div>
                </nav>
            </section>
            <!--div.game_list 游戏列表  end-->
            <div class="footer_padding"></div>
        </div>
        <!--div.z_min 内容区域 end-->
    </div>
    <!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script>$('#footer a:eq(2)').attr('id', 'footer_nav_active');</script>
</body>
</html>