<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
<meta name="keywords" content="<?php echo $game['name'],' ',$game['type'],' ',$game['classic']; ?> H5 HTML5 H5游戏 HTML5游戏 小游戏 手机游戏 网页游戏 在线游戏 点击即玩 久乐游戏 久乐H5">
<meta name="description" content="<?=$game['in_short'] ? $game['in_short'] : '久乐游戏是一个行业领先的H5在线游戏平台，玩游戏不再苦苦的等待下载，点击即玩。'?>">
<title><?=$game['name']?><?=$gift['name']?> - 久乐H5在线游戏平台</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/game_gift.css"/>
</head>
<body class="bg01">
<!--div.container 总外框  start-->
<div class="z_container">
    <header class="z_header">
        <a target="_top" href="/game/index.html"></a><span><?=$gift['name']?></span>
    </header>

    <!--div.z_min 内容区域 statr-->
    <div class="z_main" data-role="conent">
        <!--div.infos 游戏信息 statr-->
        <section class="infos game_list block_bg">
            <div class="infos_main">
                <div class="game_log relative">
                    <a><img src="<?=$game['logo']?>" alt="<?=$game['name']?>" width="100%" height="auto"/></a>
                </div>
                <div class="game_info">
                    <h3>
                        <span><?=$game['name']?></span>
                    </h3>
                    <P>
                        <span class="start_list fl"><?=$game['grade']?></span>
                        <span>人气：<b class="b"><?=$game['support']?></b></span>
                    </P>
                    <?php if($game['version']) { ?>
                    <p>版本<b class="b"><?=$game['version']?></b></p>
                    <?php } ?>
                </div>
            </div>
        </section>
        <!--div.infos 游戏信息 end-->

        <!--div.to_play 游戏功能 start-->
        <section class="game_list to_play block_bg">
            <div class="game_list_main">
                <div class="save_game fl">
                    <a id="add_favorite" data-gid="<?=$game['game_id']?>">
                        <img src="<?php echo $favorited ? '/images/game_info/info_12.png' : '/images/game_info/info_11.png'; ?>" alt="收藏" width="100%" height="auto">
                    </a>
                    <p>收藏</p>
                </div>
                <div class="game_btn">
                    <button id="start_game" class="btn_blue">开始玩</button>
                </div>
            </div>
        </section>
        <!--div.to_play 游戏功能 end-->

        <section class="get_gift">
            <h3>礼包/淘号</h3>
            <div>
                <p class="menus">
                    <span class="fl"><?=$gift['name']?></span>
                    <?php if($gift['type'] == 'limited') { ?>
                    <span class="fr green">库存：<?=($gift['nums'] - $gift['used'])?></span>
                    <?php } ?>
                </p>
                <div class="get">
                    <span>激活码：</span>
                    <input type="text" id="gift_cdkey" value="<?=$cdkey?>" readonly="readonly">
                    <?php
                        $btn_gray = '';
                        if( $cdkey )  $btn_gray = ' btn_gray';
                        elseif( $gift['type'] == 'limited' && $gift['used'] >= $gift['nums'] ) $btn_gray = ' btn_gray';
                    ?>
                    <a id="gift_get" href="javascript:void(0)" class="btn_green<?=$btn_gray?> fr">领 &nbsp;取</a>
                </div>
                <p id="gift_tips" class="tips">
                <?php if($cdkey){ echo '提示：双击或长按激活码可以复制！';  ?>
                <?php } elseif($gift['type'] == 'limited' && $gift['used'] >= $gift['nums']){echo '提示：激活码已领完，下次请早！';} ?>
                </p>
            </div>
        </section>
        <section class="get_gift">
            <h3>礼包详情：</h3>
            <p class="block_bg details">
            <?php foreach ($gift['content'] as $i=>$row) { ?>
                <?=$i ? '<br>' : ''?>
                <span><?=$row['name']?><?php if($row['nums']) echo ' x',$row['nums']; ?></span>
            <?php } ?>
            </p>
        </section>
        <section class="get_gift">
            <h3>活动规则：</h3>
            <p class="block_bg details"><?=$gift['rule']?></p>
        </section>
        <?php if($gift['howget']) { ?>
        <section class="get_gift">
            <h3>如何领取：</h3>
            <p class="block_bg details"><?=$gift['howget']?></p>
        </section>
        <?php } ?>
        <div class="footer_padding"></div>
    </div>
    <!--div.z_min 内容区域 end-->
</div>
<!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script>
$('#footer a:eq(3)').attr('id', 'footer_nav_active');
$(function(){
    //开始玩
    $('#start_game').on('tap', function(){
        var url = '/game/play.html?game_id=<?=$game['game_id']?>';
        if( '<?=$user?$user['user_id']:''?>' == '' ) {
            location.href = '/user/login.html?fwd='+encodeURIComponent(url);
        } else {
        	location.href = url;
        }
    });

	//收藏
    var favorited = <?=$favorited?'true':'false'?>;
    var loading = false;
    $('#add_favorite').tap(function(){
        if( '<?=$user?$user['user_id']:''?>' == '' ) {
            if( confirm('还未登录，是否现在去登录？') ) {
                location.href = '/user/login.html?fwd=<?=urlencode("/game/giftbag.html?game_id={$game['game_id']}")?>';
            }
        } else if( ! favorited ) {
            if( loading ) return false;
            loading = true;
            $.post('/user/addfavorite.html?game_id=<?=$game['game_id']?>', '', function(msg){
                if( msg == 'success' ) {
                    $('#add_favorite img').attr('src', '/images/game_info/info_12.png');
                	favorited = true;
                } else if( msg ) {
                    alert(msg);
                }
                loading = false;
            });
        }
    });

    //领取
    var cdkey = '<?=$cdkey?>';
    $('#gift_get').on('tap', function(){
        <?php if($gift['type'] == 'limited' && $gift['used'] >= $gift['nums']) { ?>
        return false;
        <?php } ?>
    	if( '<?=$user?$user['user_id']:''?>' == '' ) {
            if( confirm('还未登录，是否现在去登录？') ) {
                location.href = '/user/login.html?fwd=<?=urlencode("/game/giftbag.html?game_id={$game['game_id']}")?>';
            }
            return false;
        }
        if( cdkey != '' ) {
            return false;
        }
        if( loading ) return false;
        loading = true;
        $.post('/activity/sendout.html', 'gift_id=<?=$gift['gift_id']?>', function(msg){
        	loading = false;
        	cdkey = msg.cdkey;
        	$('#gift_cdkey').val(msg.cdkey);
        	if( msg.cdkey != '' ) {
        		$('#gift_get').addClass('btn_gray');
        	}
        	alert(msg.msg);
        }, 'json');
    });
});
</script>
</body>
</html>