<?php foreach ($games as $row) { ?>
<li>
<?php if($row['corner'] != 'normal') { ?>
    <i class="icons i_<?=$row['corner']?>"></i>
<?php } ?>
    <section class="list_content">
        <div class="game_log relative">
            <a target="_top" href="/game/detail.html?game_id=<?=$row['game_id']?>"><img src="<?=$row['logo']?>" width="60" height="60" alt="<?=$row['name']?>"></a>
        </div>
        <div class="game_info">
            <h3>
                <span><a target="_top" href="/game/detail.html?game_id=<?=$row['game_id']?>" style="color:#fff;"><?=$row['name']?></a></span>
            <?php if($row['label'] != 'normal') { ?>
                <i class="icons <?=$row['label']?>"></i>
            <?php } ?>
            </h3>
            <P>
                <span class="start_list fl"><?=$row['grade']?></span>
                <span>人气：<?=$row['support']?></span>
            </P>
            <p><?=$row['in_short']?></p>
        </div>
        <?php if($row['giftbag']) { ?>
        <a href="/game/giftbag.html?gift_id=<?=$row['giftbag']?>" class="icons i_lb"></a>
        <?php } ?>
        <div class="game_btn">
            <?php if($row['game_type']=='微端'):?>
                <?php if(file_exists("/www/wwwroot/code/h5/tg/dev/public/game/apk/{$row['game_id']}/".$tg_channel.'.apk')):?>
                    <a target="_top" href="<?='http://yun.zyttx.com/game/apk/'.$row['game_id'].'/'.$tg_channel.'.apk'?>" class="btn_blue">点击下载</a>
                <?php else:?>
                    <a target="_top" href="<?='http://yun.zyttx.com/admin/akpgame?game_id='.$row['game_id']?>" class="btn_blue">点击下载</a>
                <?php endif;?>
            <?php else:?>
                <a target="_top" href="/game/play.html?game_id=<?=$row['game_id']?>" class="btn_blue">开始玩</a>
            <?php endif;?>
        </div>
    </section>
</li>
<?php } ?>
