<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="keywords" content="H5 HTML5 H5游戏 HTML5游戏 小游戏 手机游戏 网页游戏 在线游戏 点击即玩 久乐游戏 久乐H5">
<meta name="description" content="久乐游戏是一个行业领先的H5在线游戏平台，玩游戏不再苦苦的等待下载，点击即玩。">
<title>游戏排行 - 久乐H5在线游戏平台</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/ranking.css"/>
</head>
<body class="bg01">
    <!--div.container 总外框  start-->
    <div data-role="page" class="z_container">

        <!--div.z_min 内容区域 statr-->
        <div class="z_main">
            <nav class="play_list">
                <div class="left_log">
                    <img src="/images/index/index_06.png" width="100%" height="auto"/>
                </div>
                <ul id="list_nav" class="ui-grid-d">
                    <li class="ui-block-a list_active" data-attr="support">人气</li>
                    <li class="ui-block-b" data-attr="new">最新</li>
                    <li class="ui-block-c" data-attr="grade">星级</li>
                </ul>
            </nav>

            <!--div.center 排行  start-->
            <section class="ui-grid-b center block_bg">
                <div class="center_main relative" style="overflow:hidden;">
                    <div class="info_table tabs">
                        <div class="title_log">
                            <img src="/public/images/icons_nav_01.png" height="auto" width="19" alt="logo"/>
                        </div>
                        <div class="title_word">
                            排行
                        </div>
                    </div>

                    <div class="btn_list ui-block-b tabs">
                        <ul id="list_btn">
                            <li class="btn_active"></li>
                            <li></li>
                            <li></li>
                        </ul>
                    </div>
                    <hr class="linear"/>
                </div>
            </section>
            <!--div.center 排行  start-->

            <section class="search">
                <input type="search" id="search_ipt" placeholder="找游戏：游戏名称、拼音或关键字" autocomplete="on" class="left_input"/>
                <input type="submit" id="search_btn" class="search_icon" value=""/>
            </section>

            <!--div.game_list 游戏列表  start-->
            <section id="list_cont" class="game_list">
                <div class="slide_cont swipe-wrap">
                    <ul id="game_list_1"></ul>
                    <ul id="game_list_2"></ul>
                    <ul id="game_list_3"></ul>
                </div>
            </section>
            <!--div.game_list 游戏列表  end-->
            <div class="footer_padding"></div>
        </div>
        <!--div.z_min 内容区域 end-->
    </div>
    <!--div.container 总外框  end-->
	<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script src="/jquery/swipe.js"></script>
<script>
window.onload = function(){
	$(".z_container ").css("min-height", "300px");
};
$('#footer a:eq(2)').attr('id', 'footer_nav_active');
//游戏动态加载
var attr_data = {
	total: {'support':-1,'new':-1,'grade':-1},
	pn:{'support':0,'new':0,'grade':0},
	loading:false
};
function getListByAttr(attr)
{
	if( attr_data.loading ) {
		return false;
	}
	var ul = '';
	switch(attr)
    {
    case 'support': ul = '#game_list_1'; break;
    case 'new': ul = '#game_list_2'; break;
    case 'grade': ul = '#game_list_3'; break;
    }
    if( $(ul).html() != '' ) {
    	$('#list_cont').height($(ul).height());
        return false;
    }
	attr_data.loading = true;
    $.ajax({
        type: 'GET',
        url: '/game/list.html?attr='+attr,
        success: function(msg){
        	attr_data.loading = false;
        	$(".ui-loader").hide();
            if( msg == '' ) {
                return false;
            }
            $(ul).html(msg);
            $('#list_cont').height($(ul).height());
            //top_swipe.slide($('#list_nav li.list_active').index(), 400);
        },
        error: function(){
        	attr_data.loading = false;
        	$(".ui-loader").hide();
        	alert('网络连接失败！');
        }
    });
}
getListByAttr('support');
$(function(){
	$(".search a.ui-input-clear").html("");
	
	window.top_swipe = new Swipe(document.getElementById('list_cont'), {
	  startSlide: 0,
	  speed: 400,
	  auto: false,
	  continuous: true,
	  disableScroll: false,
	  stopPropagation: false,
	  callback: function(index, elem) {
		  $('#list_nav li').removeClass('list_active').eq(index).addClass('list_active');
		  $('#list_btn li').removeClass('btn_active').eq(index).addClass('btn_active');
	      getListByAttr($('#list_nav li.list_active').attr('data-attr'));
	  }
	  //transitionEnd: function(index, elem) {}
	});
	$('#list_nav li').on('tap', function(){
		top_swipe.slide($(this).index(), 400);
		return true;
	});

	$('#search_btn').parent().prev().find('a.ui-btn').on('tap', function(){
		var v = $.trim($('#search_ipt').val());
		v = v.replace(/[\'\"\?`~\!\$\%\^\*\(\)\[\]\{\}\-\+\\]+/, '');
		$('#search_ipt').val(v);
		if( v == '' ) {
			alert('请输入游戏名称、拼音或关键字！');
			$('#search_ipt').focus();
			return false;
		}
		location.href = '/game/search.html?search='+ encodeURIComponent(v);
	});
});
</script>
</body>
</html>