    <div class="content-box">
      <!-- Start Content Box -->
      <div class="content-box-header">
        <h3><?=$title?></h3>
        <a class="go_back" href="javascript:history.go(-1);">返回上一页</a>
        <div class="clear"></div>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
          <form action="/admin/<?=$controller?>/cache?<?=$query?>" method="post" enctype="multipart/form-data">
            <fieldset>
            <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
            <?php if( $msg ) { ?>
            <div class="tab-content default-tab">
                <div class="notification success png_bg"> <a href="#" class="close"><img src="/admin/images/icons/cross_grey_small.png" title="Close this notification" alt="close" /></a>
                    <div><?=$msg?></div>
                </div>
            </div>
            <?php } ?>
            <p>
              <label>广告位名称</label>
              <select class="small-input" name="pos_id" required="required">
                <option value="">--选择要更新的广告位--</option>
                <option value="-1" selected="selected">全部更新</option>
              <?php foreach ($ad_pos as $pos) { ?>
                <option value="<?=$pos['pos_id']?>"><?=$pos['name']?></option>
              <?php } ?>
              </select>
            </p>
            <p>
              <input class="button" type="submit" value="提交" />
            </p>
            </fieldset>
            <div class="clear"></div>
            <!-- End .clear -->
          </form>
        </div>
        <!-- End #tab2 -->
      </div>
      <!-- End .content-box-content -->
    </div>
    <!-- End .content-box -->

    <div class="clear"></div>
