<footer>
<div class="footer_center">
    <i class="icons i_logo2"></i>
    <address>
        <p>
            <span>成都市高新区天府新谷7号楼3单元901|</span>
            <a href="#">隐私条款</a><span> |</span>
            <a href="#">法律声明</a><span> 蜀ICP备18008778号-1</span>
        </p>
        <p>&copy; Chengdu JIULE Technology Co., Ltd. 成都九九六网络科技有限公司 版权所有</p>
    </address>
</div>
</footer>
<div style="height:0; width:0; overflow:hidden;">
    <script src="http://s4.cnzz.com/z_stat.php?id=1256826566&web_id=1256826566"></script>
</div>