<!--<style>-->
<!--#namiyx_wechat{background:transparent url(/images/namiyx_wechat.png) no-repeat scroll left top;-->
<!--	height:204px; width:48px; position:absolute; right:0; top:50%; margin-top:-102px}-->
<!--</style>-->
<!--<div id="namiyx_wechat" title="关注久乐游戏微信公众号"></div>-->
<!--<script>-->
<!--$(function(){-->
<!--	var func = function(){-->
<!--    	$('#namiyx_wechat').css('top', $(window).height()/2 + $(document).scrollTop());-->
<!--    };-->
<!--    $(window).scroll(func).resize(func).trigger('scroll');-->
<!--    $('#namiyx_wechat').mouseenter(function(){-->
<!--        $(this).stop().animate({width:250});-->
<!--    }).mouseleave(function(){-->
<!--    	$(this).stop().animate({width:48});-->
<!--    });-->
<!--});-->
<!--</script>-->