<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>申请上线 - 游戏管理 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/game_api.css"/>
<style>
.ul_info .info_list{padding:3px 12px; text-align:center;}
</style>
</head>
<body class="user">
    <div class="container">
        <?php include $this->getScriptPath().'/header.phtml'; ?>
        <div class="main2">
            <div class="center">
                <?php include $this->getScriptPath().'/info_menu.phtml'; ?>
                <section class="content">
                    <header class="user_title">
                        <nav>
                            <a href="/gameinfo/index.html?game_id=<?=$game_id?>">游戏总览</a>
                            <span class="gt"> &gt; </span>
                            <strong>申请上线</strong>
                        </nav>
                    </header>
                    <article>
                        <div class="step_cont">
                            <ul class="step">
                                <li<?=$status>=2 ? ' class="choose"' : ''?>>
                                    <span class="number"> <i>1</i> </span>
                                    <i class="lines lines_right"></i>
                                    <h3>提交申请</h3>
                                </li>
                                <li<?=$status>=6 ? ' class="choose"' : ''?>>
                                    <i class="lines lines_left"></i>
                                    <span class="number"> <i>2</i> </span>
                                    <i class="lines lines_right"></i>
                                    <h3>审核通过</h3>
                                </li>
                                <li<?=$status==9 ? ' class="choose"' : ''?>>
                                    <i class="lines lines_left"></i>
                                    <span class="number"> <i>3</i> </span>
                                    <h3>上线运营</h3>
                                </li>
                            </ul>
                        </div>
                        <?php if($message) { ?>
                        <ul class="ul_info border1">
                            <li class="info_list"<?php if($status==5) echo ' style="color:red"'; ?>><?=$message?></li>
                        </ul>
                        <?php } ?>
                    </article>
                    <?php if( in_array($status, array(2,3,5,6,9)) ) { ?>
                    <footer class="buttons_group">
                    <form method="post">
                        <div class="buttons_center">
                        <?php if( in_array($status, array(2,3,5)) ) { ?>
                            <input type="submit" name="apply" value="立即申请" class="btn_green2">
                        <?php } elseif( $status == 6 ) { ?>
                            <input type="submit" name="online" value="上&nbsp;&nbsp;线" class="btn_green2">
                        <?php } /* else { ?>
                            <input type="submit" name="offline" value="下&nbsp;&nbsp;线" class="btn_green2">
                        <?php } */ ?>
                        </div>
                    </form>
                    </footer>
                    <?php } ?>
                </section>
            </div>
        </div>
        <?php include $this->getScriptPath().'/footer.phtml'; ?>
    </div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script>
<?php include $this->getScriptPath().'/info_base.js'; ?>
</script>
</body>
</html>