<script type="text/javascript" src="/js/My97DatePicker/WdatePicker.js"></script>
    <div class="content-box">
      <!-- Start Content Box -->
      <div class="content-box-header">
        <h3><?=$title?></h3>
        <a class="go_back" href="javascript:history.go(-1);">返回上一页</a>
        <div class="clear"></div>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
          <form action="/admin/<?=$controller?>/update?<?=$query?>" method="post" enctype="multipart/form-data">
          <input type="hidden" name="info[ad_id]" value="<?php echo isset($info) ? $info['ad_id'] : ''; ?>" />
            <fieldset>
            <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
            <p>
              <label>广告位</label>
              <select class="small-input" id="ad_pos" name="info[pos_id]">
              <?php foreach ($all_pos as $pos) { ?>
                <option value="<?=$pos['pos_id']?>" data-pos="<?=$pos['name']?>,<?=$pos['image']?>,<?=$pos['width']?>,<?=$pos['height']?>"<?php if(isset($ad_pos) && $ad_pos['pos_id'] == $pos['pos_id']) echo ' selected="selected"'; ?>><?=$pos['name']?></option>
              <?php } ?>
              </select>
              <input type="hidden" id="ad_name" name="info[name]" value="<?php echo isset($info) ? $info['name'] : ''; ?>" />
            </p>
            
            <p id="ad_image">
              <label>广告图片<span id="ad_wh_desc"></span></label>
              <input type="file" name="image">&nbsp;
              <?php if(isset($info) && $info['image']) echo "<a class=\"lightbox\" href=\"{$info['image']}\"><img style=\"max-height:120px;\" src=\"{$info['image']}\"></a>"; ?>
            </p>
            <p>
              <label>广告标题</label>
              <input class="text-input medium-input" type="text" name="info[subject]" value="<?php echo isset($info) ? $info['subject'] : ''; ?>" />
            </p>
            <p>
              <label>广告链接</label>
              <input class="text-input medium-input" type="text" name="info[url]" value="<?php echo isset($info) ? $info['url'] : ''; ?>" />
            </p>
            <p>
              <label>链接打开方式</label>
              <select name="info[target]">
              <?php foreach ($target as $lk=>$lv) { ?>
                <option value="<?=$lk?>"<?php if(isset($info) && $info['target'] == $lk) echo ' selected="selected"'; ?>><?=$lv?></option>
              <?php } ?>
              </select>
            </p>
            <p>
              <label>广告有效期</label>
              <input class="text-input small-input" type="text" name="info[on_time]" value="<?php echo isset($info) ? date('Y-m-d H:i:s', $info['on_time']) : ''; ?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" style="width:130px !important;" /> ~
              <input class="text-input small-input" type="text" name="info[off_time]" value="<?php echo isset($info) ? date('Y-m-d H:i:s', $info['off_time']) : ''; ?>" onclick="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})" style="width:130px !important;" />
            </p>
            
            <p>
              <label>是否可见</label>
              <select name="info[visible]">
              <?php foreach (array('1'=>'是','0'=>'否') as $lk=>$lv) { ?>
                <option value="<?=$lk?>"<?php if(isset($info) && $info['visible'] == $lk) echo ' selected="selected"'; ?>><?=$lv?></option>
              <?php } ?>
              </select>
            </p>
            <p>
              <label>显示顺序<small>（升序，最大255）</small></label>
              <input class="text-input small-input" type="text" name="info[display]" value="<?php echo isset($info) ? $info['display'] : '0'; ?>" />
            </p>
            <p>
              <input class="button" type="submit" value="提交" />
            </p>
            </fieldset>
            <div class="clear"></div>
            <!-- End .clear -->
          </form>
        </div>
        <!-- End #tab2 -->
      </div>
      <!-- End .content-box-content -->
    </div>
    <!-- End .content-box -->

    <div class="clear"></div>

<script>
$(function(){
    var data_pos = $('#ad_pos option:selected').attr('data-pos');
	var func = function(data_pos){
		var data = data_pos.split(',');
		$('#ad_name').val(data[0]);
		if( data[1] != '' ) {
			$('#ad_image').slideDown();
			$('#ad_wh_desc').html('（'+data[2]+'x'+data[3]+'）');
		} else {
			$('#ad_image').slideUp().find('input').val('');
			$('#ad_wh_desc').html('');
		}
	};
	func(data_pos);
	$('#ad_pos').change(function(){
		func($('#ad_pos option:selected').attr('data-pos'));
	});
});
</script>
