<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>找回密码 - 管理中心 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/user_public.css"/>
<link rel="stylesheet" href="/js/dxj-alert/dxj-alert.css"/>
</head>
<body class="user">
<div class="container">
    <?php include $this->getScriptPath().'/header.phtml'; ?>
    <div class="main2">
        <div class="center">
            <section class="content">
                <div class="user_title">
                    <nav>
                        <a href="/developer/login.html">返回登录</a>
                        <span class="gt"> &gt; </span>
                        <strong>找回密码</strong>
                    </nav>
                </div>
                <form class="form_edit" id="js_validate" method="post">
                    <div>
                        <label>登录邮箱</label>
                        <input type="text" placeholder="请填输入登录邮箱" class="widen" id="email" name="email"/>
                    </div>
                    <div>
                        <label>验证码</label>
                        <input type="text" placeholder="请填输入图片验证码" class="verification" id="xcode" name="xcode" maxlength="4"/>
                        <img src="/imgcode/developer.html?<?=mt_rand()?>" width="103" height="auto" style="float:left; margin-left:12px"/>
                    </div>
                    <div class="btn_group" style="display:block">
                        <label></label>
                        <input type="button" id="send" value="发送找回邮件" style="width:120px"/>
                    </div>
                </form>
            </section>
        </div>
    </div>
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/dxj-alert/dxj-alert.js"></script>
<script src="/js/jquery.validate.min.js"></script>
<script>
<?php include $this->getScriptPath().'/base.js'; ?>
$(function(){
	function xcode()
	{
		var src = '/imgcode/developer.html?';
    	src += Math.random().toString().replace(/^0\./, '');
    	$('#xcode').next().attr('src', src);
	}
	var refresh = true;
    $('#xcode').next().click(function(){
        if( ! refresh ) return false;
        refresh = false;
        xcode();
    	setTimeout(function(){
    		refresh = true;
    	}, 3000);
    });

    $("#js_validate").validate({
        rules:{
        	email: {
                required: true,
                maxlength:32
            },
            xcode: {
                required: true,
                rangelength:[4,4]
            }
        },
        messages:{
        	email: {
                required: "登录邮箱不能为空",
                maxlength:"请输入不超过32位长度的邮箱地址"
            },
            xcode: {
                required: "图片验证码不能为空",
                rangelength:"验证码为4位字母或数字的组合"
            }
        }
    });
    var loading = false;
    var timer = null;
    $('#send').click(function(){
        if( loading || timer ) return false;
        if( $('#js_validate').valid() ) {
        	loading = true;
        	$.post('/emailcode/forget.html', $('#js_validate').serialize(), function(msg){
        		loading = false;
            	if( msg.msg == 'success' ) {
            		$('#send').replaceWith('<span style="float:left; line-height:32px; font-size:14px; color:green">找回密码的邮件已经发出，请根据邮箱中的提示进行下一步操作。</span>');
            	} else {
            		dxjalert(msg.msg, 'error');
            		if( msg.xcode == 'refresh' ) {
                		xcode();
            		}
            		var count = 60;
            		timer = setInterval(function(){
                		--count;
                		if( count < 0 ) {
                			$('#send').val('发送找回邮件');
                			clearInterval(timer);
                			timer = null;
                		} else {
                			$('#send').val('重新发送（'+count+'）');
                		}
            		}, 1000);
            	}
        	}, 'json');
        }
    });
});
</script>
</body>
</html>