<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="keywords" content="H5 HTML5 H5游戏 HTML5游戏 小游戏 手机游戏 网页游戏 在线游戏 点击即玩 久乐游戏 久乐H5 H5平台 签到 活动 规则">
<meta name="description" content="久乐游戏是一个行业领先的H5在线游戏平台，玩游戏不再苦苦的等待下载，点击即玩。">
<title>签到活动规则 - 久乐H5在线游戏平台</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<style>
    .main{
        height: auto;
        padding: 10px;
        color: #FFFFFF;
        margin-bottom: 20px;
    }
    .main h1,h3,p{
        font-weight: 100;
    }
    .main h1{
        padding: 10px;
        color: #FFFFFF;
        height: auto;
        text-align: center;
    }
    .main h3{
        font-size: 14px;
        height: auto;
        line-height: 25px;
    }
    .main p{
        text-indent: 2em;
        color: #C6CFD2;
        line-height: 20px;
    }
</style>
</head>
<body>
<div class="bg01"></div>
<div class="wrapper">
    <header class="z_header">
        <a href="/signreward/index.html"></a><sapn>返回</sapn>
    </header>
    <div class="main">
        <h1>签到活动详细规则</h1>
        <h3>1、连续签到</h3>
        <p>连续签到第一天50积分，第二天100积分，第三天150积分，第四天200积分，之后保持连续签到，均可每日获得200积分。如果中途中断，则重新开始。</p>
        <h3>2、累计签到</h3>
        <p>累计签到10天500积分，20天1000积分，30天2000积分，每累计到30天，累计天数重新开始。</p>
        <h3>3、积分的说明</h3>
        <p>目前平台币与积分的汇率暂定为1：1000。积分的用法正在商定中，尽请期待。</p>
    </div>
    <div class="footer_padding"></div>
</div>
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script>$('#footer a:eq(3)').attr('id', 'footer_nav_active');</script>
</body>
</html>