<style>
    p a{
        text-align: center;
        text-decoration:underline;
    }
</style>
<footer>
<div class="footer_center">
<!--    <i class="icons i_logo2"></i>-->
    <address>
        <p>
            <a target="_blank" href="http://www.jjlwl.com/public/jianhu.html">家长监护工程|</a>
            <a target="_blank" href="http://www.jjlwl.com/public/jianhu.html">家长监护工程|</a>
            <a target="_blank" href="http://h5.zyttx.com">游戏平台|</a>
            <a target="_blank" href="http://open.zyttx.com/">开放平台|</a>
            <a target="_blank" href="http://yun.zyttx.com">推广平台</a>
        </p>
        <p>
            <span>网络文化经营许可证：川网文[2018]7147-249号  增值电信业务经营许可证: 办理中  蜀ICP备18008778-1号</span>
<!--            <a href="#">隐私条款</a><span> |</span>-->
<!--            <a href="#">法律声明</a><span> 蜀ICP备18008778号-1</span>-->
        </p>
        <p>&copy; Chengdu JIULE Technology Co., Ltd. 成都九九六网络科技有限公司 版权所有</p>
    </address>
</div>
</footer>
<!--<div style="height:0; width:0; overflow:hidden;">-->
<!--    <script src="http://s4.cnzz.com/z_stat.php?id=1256826566&web_id=1256826566"></script>-->
<!--</div>-->