<?php
$fwd = isset($_SERVER['REQUEST_URI']) ? '?fwd='.urlencode($_SERVER['REQUEST_URI']) : '';
if( !isset($dev) ) {
    $m_dev = F_Model_Pdo::getInstance('Developer');
    $dev = $m_dev->getLogin();
    if( $dev ) {
        $username = $m_dev->formatUsername($dev['username']);
    }
} else if( $dev ) {
    $m_dev = F_Model_Pdo::getInstance('Developer');
    $username = $m_dev->formatUsername($dev['username']);
}
?>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
<header>
    <div class="header_main">
        <a href="/" class="icons i_logo"></a>
        <nav id="top_nav">
            <a href="/">首页</a>
            <a href="/documents/index.html">关于我们</a>
            <a href="/nami/contactus.html">联系我们</a>
        </nav>
    </div>
    <hr class="line"/>
</header>
<?php unset($fwd); ?>