<div class="content-box">
    <!-- Start Content Box -->
    <div class="content-box-header">
        <h3><?= $title ?></h3>
        <a class="go_back" href="javascript:history.go(-1);">返回上一页</a>
        <div class="clear"></div>
    </div>
    <!-- End .content-box-header -->
    <div class="content-box-content">
        <div class="tab-content default-tab">
            <form action="/admin/admin/update" method="post">
                <input type="hidden" name="info[admin_id]"
                       value="<?php echo isset($info) ? $info['admin_id'] : ''; ?>"/>
                <fieldset>
                    <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
                    <p>
                        <label>渠道账号</label>
                        <input class="text-input small-input" type="text" id="username" name="info[username]"
                               value="<?php echo isset($info) ? $info['username'] : ''; ?>" <?php echo isset($info)?'readonly':'';?>/>
                        <br/>
                    </p>
                    <p>
                        <label>用户密码</label>
                        <input class="text-input small-input" type="password" id="upass" name="info[password]"
                               value=""/>
                        <br/>
                    </p>
                    <p>
                        <label>真实姓名</label>
                        <input class="text-input small-input" type="text" id="nickname" name="info[nickname]"
                               value="<?php echo isset($info) ? $info['nickname'] : ''; ?>"/>
                        <br/>
                    </p>
                    <p>
                        <label>支付宝账号</label>
                        <input class="text-input small-input" type="text" id="pay_number" name="info[pay_number]"
                               value="<?php echo isset($info) ? $info['pay_number'] : ''; ?>"/>
                        <br/>
                    </p>
                    <p>
                    <p>
                        <label>盒子名称</label>
                        <input class="text-input small-input" type="text" id="boxname" name="info[boxname]"
                               value="<?php echo isset($info) ? $info['boxname'] : ''; ?>"/>
                        <br/>
                    </p>
                    <p>
                        <label>分成比例</label>
                        <input class="text-input small-input" type="number" id="boxname" name="info[divide_into]"
                               value="<?php echo isset($info) ? $info['divide_into'] : ''; ?>" min="0" max="55"/>
                        <br/>
                    </p>
                    <p>
                        <label>客服QQ</label>
                        <input class="text-input small-input" type="number"  name="info[qq1]"
                               value="<?php echo isset($info) ? $info['qq1'] : ''; ?>"/>
                        <br/>
                    </p>
                    <p>
                        <label>QQ群</label>
                        <input class="text-input small-input" type="number"  name="info[qq2]"
                               value="<?php echo isset($info) ? $info['qq2'] : ''; ?>"/>
                        <br/>
                    </p>


                    <input type="hidden" name="info[status]" value="super">
                    <input class="button" type="submit" value="提交"/>
                    </p>
                </fieldset>
                <div class="clear"></div>
                <!-- End .clear -->
            </form>
        </div>
        <!-- End #tab2 -->
    </div>
    <!-- End .content-box-content -->
</div>
<!-- End .content-box -->

<div class="clear"></div>
