<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>编辑API - 游戏管理 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/game_api.css"/>
</head>
<body class="user">
    <div class="container">
        <?php include $this->getScriptPath().'/header.phtml'; ?>
        <div class="main2">
            <div class="center">
                <?php include $this->getScriptPath().'/info_menu.phtml'; ?>
                <section class="content">
                    <header class="user_title">
                        <nav>
                            <a href="/gameinfo/index.html?game_id=<?=$game_id?>">游戏总览</a>
                            <span class="gt"> &gt; </span>
                            <a href="/gameinfo/apiinfo.html?game_id=<?=$game_id?>">API接入</a>
                            <span class="gt"> &gt; </span>
                            <strong>编辑</strong>
                        </nav>
                    </header>
                    <article>
                        <div class="top_title">
                            <h3>请参考这些文档，完成API的接入，并补全下面的资料，以便通过审核</h3>
                            <p>在线查看：
                            <?php foreach ($doc['ads'] as $i=>$row) { ?>
                                <a href="<?=$row['url']?>" class="green"><?=$row['subject']?></a><?=($i==0)?' |':''?>
                            <?php } ?>
                            </p>
                        </div>
                        <form class="ul_info" id="js_validate" method="post">
                            <div class="info_list">
                                <strong>游戏ID：</strong>
                                <span><?=$game_id?></span>
                            </div>
                            <div class="info_list">
                                <strong>游戏KEY：</strong>
                                <span><?=$sign_key?></span>
                            </div>
                            <div class="info_list">
                                <label class="labels"> 登录接口地址：</label>
                                <input type="text" id="login_url" name="login_url" placeholder="微端游戏不用填写" value="<?=$login_url?>" />
                            </div>
                            <div class="info_list">
                                <label class="labels"> 充值接口地址：</label>
                                <input type="text" id="recharge_url" name="recharge_url" placeholder="免费游戏不用填写" value="<?=$recharge_url?>" />
                            </div>
                            <div class="info_list">
                                <label class="labels"> 是否支持平台发起充值：</label>
                                <select id="prepay" name="prepay">
                                <?php foreach (array(0=>'否',1=>'是') as $k=>$v) { ?>
                                    <option value="<?=$k?>"<?php if($k == $prepay) echo ' selected="selected"'; ?>><?=$v?></option>
                                <?php } ?>
                                </select>
                            </div>
                        </form>
                    </article>
                    <footer class="buttons_group">
                        <div class="buttons_center">
                            <input type="button" id="save" value="保存信息" class="btn_green2 fl">
                            <button onclick="javascript:location.href='/gameinfo/baseinfo.html?game_id=<?=$game_id?>';return false;" class="btn_white fl">取消修改</button>
                        </div>
                    </footer>
                </section>
            </div>
        </div>
        <?php include $this->getScriptPath().'/footer.phtml'; ?>
    </div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/jquery.validate.min.js"></script>
<script>
<?php include $this->getScriptPath().'/info_base.js'; ?>
$(function(){
    $("#js_validate").validate({
        rules:{
        	login_url: {
                maxlength:128
            },
            recharge_url: {
                maxlength:128
            }
        },
        messages:{
        	login_url: {
                maxlength:"登录接口地址的长度限制为128位"
            },
            recharge_url: {
                maxlength:"充值接口地址的长度限制为128位"
            }
        }
    });
    $('#save').click(function(event){
        event.preventDefault();
        if( $("#js_validate").valid() ) {
        	$("#js_validate").get(0).submit();
        }
        return false;
    });
});
</script>
</body>
</html>