<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>银行账号 - 管理中心 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/user_public.css"/>
</head>
<body class="user">
<div class="container">
    <?php include $this->getScriptPath().'/header.phtml'; ?>
    <div class="main2">
        <div class="center">
            <?php include $this->getScriptPath().'/menu.phtml'; ?>
            <section class="content">
                <div class="user_title">
                    <nav>
                        <a href="/developer/index.html">账号中心</a>
                        <span class="gt"> &gt; </span>
                        <strong>银行账号</strong>
                    </nav>
                    <a href="/developer/editbank.html">
                        <i class="icons i_edit2"></i><span>编辑</span>
                    </a>
                </div>
                <ul class="company_info">
                    <li>
                        <strong> <i class="red">*</i> 银行</strong>
                        <span><?=$dev['bank_name']?></span>
                    </li>
                    <li>
                        <strong> <i class="red">*</i> 开户行名称</strong>
                        <span><?=$dev['bank_open']?></span>
                    </li>
                    <li>
                        <strong> <i class="red">*</i> 账户名</strong>
                        <span><?=$dev['bank_user']?></span>
                    </li>
                    <li>
                        <strong> <i class="red">*</i> 银行账号</strong>
                        <span><?=$dev['bank_no']?></span>
                    </li>
                    <li>
                        <strong> 对账人</strong>
                        <span><?=$dev['bank_check']?></span>
                    </li>
                    <li>
                        <strong>对账人电话</strong>
                        <span><?=$dev['bank_ck_mobile']?></span>
                    </li>
                </ul>
            </section>
        </div>
    </div>
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</div>
<script src="/js/jquery-1.4.2.min.js"></script>
<script>
<?php include $this->getScriptPath().'/base.js'; ?>
</script>
</body>
</html>