<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>证件资质 - 管理中心 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/user_public.css"/>
<link rel="stylesheet" href="/js/Magnific-Popup/magnific-popup.css"/>
<style>
.papers h3{color:red; font-weight:normal; padding:0 0 20px;}
img.popup{cursor:pointer;}
</style>
</head>
<body class="user">
<div class="container">
    <?php include $this->getScriptPath().'/header.phtml'; ?>
    <div class="main2">
        <div class="center">
            <?php include $this->getScriptPath().'/menu.phtml'; ?>
            <section class="content">
                <div class="user_title">
                    <nav>
                        <a href="/developer/index.html">账号中心</a>
                        <span class="gt"> &gt; </span>
                        <strong>证件上传</strong>
                    </nav>
                    <a href="/developer/upload.html" id="edit">
                        <i class="icons i_edit2"></i><span>编辑</span>
                    </a>
                </div>
                <div class="papers">
                    <figure class="fl">
                    <?php if( $dev['org_img'] ) { ?>
                        <img src="<?=$dev['org_img']?>" href="<?=$dev['org_img']?>" width="340" height="auto" class="popup"/>
                    <?php } else { ?>
                        <h3>还未上传</h3>
                    <?php } ?>
                        <figcaption><?=$dev['type']=='company'? '组织机构代码证' : '身份证正面'?></figcaption>
                    </figure>
                    <figure class="fr">
                    <?php if( $dev['lic_img'] ) { ?>
                        <img src="<?=$dev['lic_img']?>" href="<?=$dev['lic_img']?>" width="170" height="auto" class="popup"/>
                    <?php } else { ?>
                        <h3>还未上传</h3>
                    <?php } ?>
                        <figcaption><?=$dev['type']=='company'? '营业执照' : '身份证背面'?></figcaption>
                    </figure>
                </div>
            </section>
        </div>
    </div>
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/Magnific-Popup/jquery.magnific-popup.min.js"></script>
<script>
<?php include $this->getScriptPath().'/base.js'; ?>
$(function(){
    $('img.popup').magnificPopup({
        type: 'image',
        closeOnContentClick: true,
        mainClass: 'mfp-img-mobile',
        image: {
            verticalFit: true
        }
    });
});
</script>
</body>
</html>