<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>修改密码 - 管理中心 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/user_public.css"/>
<link rel="stylesheet" href="/js/dxj-alert/dxj-alert.css"/>
</head>
<body class="user">
<div class="container">
    <?php include $this->getScriptPath().'/header.phtml'; ?>
    <div class="main2">
        <div class="center">
            <?php include $this->getScriptPath().'/menu.phtml'; ?>
            <section class="content">
                <div class="user_title">
                    <nav>
                        <a href="/developer/index.html">账号中心</a>
                        <span class="gt"> &gt; </span>
                        <strong>修改密码</strong>
                    </nav>
                </div>
                <form class="form_edit" id="js_validate" method="post">
                    <div>
                        <label>原密码</label>
                        <input type="password" placeholder="请填输入原密码" class="widen" id="oldpwd" name="oldpwd"/>
                    </div>
                    <div>
                        <label>新密码</label>
                        <input type="password" placeholder="请填输入新密码" class="widen" id="newpwd" name="newpwd"/>
                    </div>
                    <div>
                        <label>确认新密码</label>
                        <input type="password" placeholder="请再次输入新密码" class="widen" id="re_pwd" name="re_pwd"/>
                    </div>

                    <div class="btn_group">
                        <input type="submit" value="修改密码"  />
                    </div>
                </form>
            </section>
        </div>
    </div>
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/dxj-alert/dxj-alert.js"></script>
<script src="/js/jquery.validate.min.js"></script>
<script>
<?php include $this->getScriptPath().'/base.js'; ?>
$(function(){
    /**自定义  确认新密码*/
    $.validator.addMethod("isSure",function(value,element,params){
        var sure = $("#re_pwd").val();
        var news = $("#newpwd").val();
        if(sure == news){
            return true;
        }else{
            return false;
        }
    },"两次输入必须一致");

    var loading = false;
    $("#js_validate").validate({
        rules:{
            oldpwd: {
                required: true,
                rangelength:[6,20]
            },
            newpwd: {
                required: true,
                rangelength:[6,20]
            },
            re_pwd: {
                required: true,
                isSure:true
            }
        },
        messages:{
        	oldpwd: {
                required: "原密码不能为空",
                rangelength:"原密码输入不正确"
            },
            newpwd: {
                required: "新密码不能为空",
                rangelength:"密码由6-20位字母、数字或字符组成"
            },
            re_pwd: {
                required: "确认密码不能为空",
                isSure:"两次密码输入不一致"
            }
        },
        submitHandler: function(form){
            if( loading ) return false;
            if( $('#js_validate').valid() ) {
            	loading = true;
            	$.post('/developer/password.html', $('#js_validate').serialize(), function(msg){
                	if( msg.fwd != '' ) {
                		var type = 'success';
                		var func = function(){location.href=msg.fwd};
                		var opt = {
                        	onOk:func, onCancle:func, onClose:func
                		};
            		} else {
            			var type = 'error';
            			var opt = {};
            		}
                	dxjalert(msg.msg, type, opt);
                	loading = false;
            	}, 'json');
            }
        }
    });
});
</script>
</body>
</html>