<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>证件上传 - 管理中心 久乐游戏开发者平台</title>
<link rel="stylesheet" href="/css/base.css"/>
<link rel="stylesheet" href="/css/user_public.css"/>
<link rel="stylesheet" href="/js/dxj-alert/dxj-alert.css"/>
<link rel="stylesheet" href="/js/Magnific-Popup/magnific-popup.css"/>
<style>
.papers h3{color:red; font-weight:normal; padding:0 0 20px;}
input.file{border:none; cursor:pointer; height:37px; margin-left:-82px; filter:alpha(opacity=0); opacity:0; overflow:hidden; width:80px; z-index:1;}
img.popup{cursor:pointer;}
</style>
</head>
<body class="user">
<div class="container">
    <?php include $this->getScriptPath().'/header.phtml'; ?>
    <div class="main2">
        <div class="center">
            <?php include $this->getScriptPath().'/menu.phtml'; ?>
            <section class="content">
                <header class="user_title">
                    <nav>
                        <a href="/developer/index.html">账号中心</a>
                        <span class="gt"> &gt; </span>
                        <a href="/developer/papers.html">证件上传</a>
                        <span class="gt"> &gt; </span>
                        <strong>编辑</strong>
                    </nav>
                </header>
                <form id="form_up" action="" method="post" enctype="multipart/form-data">
                <article class="papers">
                    <figure class="fl">
                    <?php if( $dev['org_img'] ) { ?>
                        <img src="<?=$dev['org_img']?>" href="<?=$dev['org_img']?>" width="340" height="auto" class="popup"/>
                    <?php } else { ?>
                        <h3>还未上传</h3>
                    <?php } ?>
                        <figcaption><?=$dev['type']=='company'? '组织机构代码证' : '身份证正面'?></figcaption>
                        <button class="btn_white">上传图片</button>
                        <input type="file" class="file" id="org_img" name="org_img">
                        <span id="org_fn"></span>
                    </figure>
                    <figure  class="fr">
                    <?php if( $dev['lic_img'] ) { ?>
                        <img src="<?=$dev['lic_img']?>" href="<?=$dev['lic_img']?>" width="170" height="auto" class="popup"/>
                    <?php } else { ?>
                        <h3>还未上传</h3>
                    <?php } ?>
                        <figcaption><?=$dev['type']=='company'? '营业执照' : '身份证背面'?></figcaption>
                        <button class="btn_white">上传图片</button>
                        <input type="file" class="file" id="lic_img" name="lic_img">
                        <span id="lic_fn"></span>
                    </figure>
                </article>
                <footer class="buttons_group">
                    <div class="buttons_center">
                        <input type="button" value="保存信息" id="save" class="btn_green2 fl"/>
                        <button class="btn_white fl" onclick="javascript:history.go(-1);return false;">取消修改</button>
                    </div>
                </footer>
                </form>
            </section>
        </div>
    </div>
    <?php include $this->getScriptPath().'/footer.phtml'; ?>
</div>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/dxj-alert/dxj-alert.js"></script>
<script src="/js/Magnific-Popup/jquery.magnific-popup.min.js"></script>
<script>
<?php include $this->getScriptPath().'/base.js'; ?>
$(function(){
	$('#org_img,#lic_img').change(function(){
		if( this.files.length < 1 ) return false;
		var t = this.files[0].type;
		if( t != 'image/jpeg' && t != 'image/png' && t != 'image/gif' ) {
			dxjalert('请选择PNG、JPG或GIF格式的图片！', 'error');
			this.value = '';
			this.files = [];
		}
		if( this.value && this.files[0].size > 500*1024 ) {
			dxjalert('图片太大了，500K的限额应该知足了哦！', 'error');
			this.value = '';
			this.files = [];
		}
		$('#'+this.id.replace(/_img/,'_fn')).html(this.value);
		return true;
	});
	$('#save').click(function(){
		if( $('#org_img').val() != '' || $('#lic_img').val() != '' ) {
			$('#form_up').submit();
		} else {
			return false;
		}
	});

	$('img.popup').magnificPopup({
        type: 'image',
        closeOnContentClick: true,
        mainClass: 'mfp-img-mobile',
        image: {
            verticalFit: true
        }
    });
});
</script>
</body>
</html>