<!--footer 底部 start-->
<?php
    var_dump($params);
?>
<div style="margin: 0 auto;text-align: center">
    恭喜来到测试游戏<br/>
    <h1>测试充值</h1>
    <form action="/test/pay" method="get">
        用户id:<input type="text" name="user_id" value="<?=$params['user_id']?>"/><br/>
        用户名:<input type="text" name="username" value="<?=$params['username']?>"/><br/>
        游戏id:<input type="text" name="game_id" value="<?=$params['game_id']?>"/><br/>
        区/服:<input type="text" name="server_id" value="<?=$params['server_id']?>"/><br/>
        金额:<input type="number" name="money" value="" required/><br/>
        标题:<input type="text" name="subject" value="测试游戏充值"/><br/>
        描述: <input type="text" name="body" value="充值了金额"/><br/>
<!--        充值id:<input type="text" name="cp_order" value=""/><br/>-->
        返回地址:<input type="text" name="cp_return" value="http://www.h5.com/test/login"/><br/>
<!--        时间:<input type="text" name="time" value="--><?//=$params['time']?><!--"/><br/>-->
        额外信息<input type="text" name="extra" value=""/><br/>
<!--        签名:<input type="text" name="sign" value=""/><br/>-->
        <button id="btn" type="submit">充值</button>
    </form>
    <script src="/public/scripts/jquery-1.11.1.min.js"></script>
</div>
<!--footer 底部  end-->
<!--<div style="width:0;height:0;overflow:hidden;"><script src="http://s95.cnzz.com/z_stat.php?id=1256660450&web_id=1256660450"></script></div>-->
