    <div class="content-box">
      <!-- Start Content Box -->
      <div class="content-box-header">
        <h3><?=$title?></h3>
        <a class="go_back" href="javascript:history.go(-1);">返回上一页</a>
        <div class="clear"></div>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
          <form action="/admin/admin/update" method="post">
          <input type="hidden" name="info[admin_id]" value="<?php echo isset($info) ? $info['admin_id'] : ''; ?>" />
            <fieldset>
            <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
            <p>
              <label>用 户 名</label>
              <input class="text-input small-input" type="text" id="uname" name="info[username]" value="<?php echo isset($info) ? $info['username'] : ''; ?>" />
              <br />
            </p>
              <p>
              <label>用户密码</label>
              <input class="text-input small-input" type="password" id="upass" name="info[password]" value="" />
              <br />
            </p>
            
            <p>
              <label>用户类型</label>
              <select id="info_status" name="info[status]" class="small-input">
                <option value="normal">普通管理员</option>
                <option value="super">超级管理员</option>
                <option value="disabled">禁用</option>
              </select>
              <script>$('#info_status').val('<?php echo isset($info) ? $info['status'] : 'normal'; ?>');</script>
            </p>
           <p>
              <label>权限组</label>
              <?=$groups?>
            </p>
            <p>
              <input class="button" type="submit" value="提交" />
            </p>
            </fieldset>
            <div class="clear"></div>
            <!-- End .clear -->
          </form>
        </div>
        <!-- End #tab2 -->
      </div>
      <!-- End .content-box-content -->
    </div>
    <!-- End .content-box -->

    <div class="clear"></div>
