<div class="content-box">
  <!-- Start Content Box -->
  <div class="content-box-header">
    <h3><?=$title?></h3>
    <a class="go_back" href="javascript:history.go(-1);">返回上一页</a>
    <div class="clear"></div>
  </div>
  <!-- End .content-box-header -->
  <div class="content-box-content">
    <div class="tab-content default-tab">
      <form action="/admin/<?=$controller?>/update?<?=$query?>" method="post">
      <input type="hidden" name="info[<?=$primary?>]" value="<?php echo isset($info) ? $info[$primary] : ''; ?>" />
        <fieldset>
        <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
        <p>
          <label>开发者ID</label>
          <span><?=$info['dev_id']?></span>
        </p>
        <p>
          <label>游戏ID</label>
          <span><?=$info['game_id']?></span>
        </p>
        <p>
          <label>游戏名称</label>
          <span><?=$info['name']?></span>
        </p>
        <p>
          <label>登录测试</label>
          <span><?=$info['login']?></span>
        </p>
        <p>
          <label>充值测试</label>
          <span><?=$info['recharge']?></span>
        </p>
        
        <p>
          <label>游戏状态</label>
          <select id="status" name="info[status]">
          <?php foreach ($op_stt as $lk=>$lv) { ?>
            <option value="<?=$lk?>"<?php if($info['status'] == $lk) echo ' selected="selected"'; ?>><?=$lv?></option>
          <?php } ?>
          </select>
        </p>
        <p id="msg_p"<?=$info['status'] != 5 ? ' style="display:none"' : ''?>>
          <label>拒绝理由</label>
          <input type="text" class="text-input medium-input" id="msg_t" name="info[message]" value="<?=$info['message']?>" placeholder="如果拒绝申请或下线游戏，请告诉开发者为什么" />
        </p>
        <p>
          <input class="button" type="button" id="save" value="提交" />
        </p>
        </fieldset>
        <div class="clear"></div>
        <!-- End .clear -->
      </form>
    </div>
    <!-- End #tab2 -->
  </div>
  <!-- End .content-box-content -->
</div>
<!-- End .content-box -->
<div class="clear"></div>
<link rel="stylesheet" href="/js/dxj-alert/dxj-alert.css"/>
<script src="/js/dxj-alert/dxj-alert.js"></script>
<script>
$(function(){
	$('#status').change(function(){
		if( this.value == 5 ) {
			$('#msg_p').slideDown();
		} else {
			$('#msg_p').slideUp();
			$('#msg_t').val('');
		}
	});
	$('#save').click(function(){
		var s = $('#status').val();
		var t = $('#msg_t').val();
		if( s == 5 && t == '' ) {
			alert('请输入拒绝理由！');
			$('#msg_t').focus();
			return false;
		} else {
			document.forms[0].submit();
		}
	});

	var loading = false;
	$('#recharge').click(function(event){
		event.preventDefault();
		if( loading ) return false;
		var m = parseInt($('#money').val());
		if( isNaN(m) || m < 1 || m > 99 ) {
			$('#money').val(1);
			dxjalert('请输入一个数字（1~99）', 'error');
			return false;
		}
		loading = true;
		$.post('/admin/devgames/prepay.html?game_id=<?=$info['game_id']?>', 'money='+m, function(msg){
			loading = false;
			if( msg == 'success' ) {
				dxjalert('充值成功，进入游戏或后台查看订单是否充值到账吧！', 'success');
			} else if(msg) {
			    dxjalert(msg, 'error');
			}
		}, 'text');
	});
});
</script>
