    <div class="content-box">
      <!-- Start Content Box -->
      <div class="content-box-header">
        <h3><?=$title?></h3>
        <a class="go_back" href="javascript:history.go(-1);">返回上一页</a>
        <div class="clear"></div>
      </div>
      <!-- End .content-box-header -->
      <div class="content-box-content">
        <div class="tab-content default-tab">
          <form action="/admin/<?=$controller?>/update?<?=$query?>" method="post" enctype="multipart/form-data">
          <input type="hidden" name="info[<?=$primary?>]" value="<?php echo isset($info) ? $info[$primary] : ''; ?>" />
            <fieldset>
            <!-- Set class to "column-left" or "column-right" on fieldsets to divide the form into columns -->
            <p>
              <label>菜单名称</label>
              <input class="text-input small-input" type="text" name="info[name]" value="<?php echo isset($info) ? $info['name'] : ''; ?>" />
            </p>
            <p>
              <label>上级菜单</label>
              <select name="info[parent_id]">
                <option value="0">--顶级菜单--</option>
              <?php foreach ($parents as $menu) { ?>
                <option value="<?=$menu['menu_id']?>"<?php if(isset($info) && $info['parent_id'] == $menu['menu_id']) echo ' selected="selected"'; ?>><?=$menu['name']?></option>
              <?php } ?>
              </select>
            </p>
            
            <p>
              <label>控制器</label>
              <input class="text-input small-input" type="text" name="info[controller]" value="<?php echo isset($info) ? $info['controller'] : ''; ?>" />
            </p>
            <p>
              <label>动作</label>
              <input class="text-input small-input" type="text" name="info[action]" value="<?php echo isset($info) ? $info['action'] : ''; ?>" />
            </p>
            
            <p>
              <label>显示顺序</label>
              <input class="text-input small-input" type="text" name="info[display]" value="<?php echo isset($info) ? $info['display'] : ''; ?>" />
              <small>值越小顺序越靠前</small>
            </p>
            
            <p>
              <label>是否可见</label>
              <select name="info[visible]">
              <?php foreach (array('1'=>'是','0'=>'否') as $lk=>$lv) { ?>
                <option value="<?=$lk?>"<?php if(isset($info) && $info['visible'] == $lk) echo ' selected="selected"'; ?>><?=$lv?></option>
              <?php } ?>
              </select>
            </p>
            <p>
              <input class="button" type="submit" value="提交" />
            </p>
            </fieldset>
            <div class="clear"></div>
            <!-- End .clear -->
          </form>
        </div>
        <!-- End #tab2 -->
      </div>
      <!-- End .content-box-content -->
    </div>
    <!-- End .content-box -->

    <div class="clear"></div>
